#include "html_page.h"

// Stored in flash (RODATA) — does not consume heap
static const char HTML_PAGE[] =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"<meta charset='utf-8'>\n"
"<meta name='viewport' content='width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no'>\n"
"<title>ESP32 Car</title>\n"
"<link href='https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;600;700&family=Share+Tech+Mono&display=swap' rel='stylesheet'>\n"
"<style>\n"
":root{"
"--bg:#090c12;--panel:rgba(13,17,26,0.97);--border:rgba(0,200,255,0.18);"
"--accent:#00c8ff;--accent2:#ff4b2b;--accent3:#00ff88;--warn:#ffcc00;"
"--text:#d0e8f0;--dim:#607080;--ram:#ff3300;"
"}\n"
"*{box-sizing:border-box;margin:0;padding:0;-webkit-tap-highlight-color:transparent;}\n"
"body{font-family:'Rajdhani',sans-serif;background:var(--bg);color:var(--text);min-height:100vh;"
"background-image:radial-gradient(ellipse 80% 40% at 50% -10%,rgba(0,200,255,0.07) 0%,transparent 70%),"
"repeating-linear-gradient(0deg,transparent,transparent 39px,rgba(0,200,255,0.03) 40px),"
"repeating-linear-gradient(90deg,transparent,transparent 39px,rgba(0,200,255,0.03) 40px);}\n"
"header{padding:10px 16px;background:rgba(0,0,0,0.75);border-bottom:1px solid var(--border);"
"display:flex;align-items:center;justify-content:space-between;position:sticky;top:0;z-index:20;"
"backdrop-filter:blur(10px);}\n"
"header h1{font-size:20px;font-weight:700;letter-spacing:3px;color:var(--accent);text-shadow:0 0 12px rgba(0,200,255,0.5);}\n"
"header small{font-family:'Share Tech Mono';font-size:10px;color:var(--dim);}\n"
"#pingBar{height:3px;background:transparent;transition:background 0.3s;}\n"
".grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:12px;max-width:900px;margin:0 auto;}\n"
"@media(max-width:600px){.grid{grid-template-columns:1fr;}}\n"
".panel{background:var(--panel);border:1px solid var(--border);border-radius:12px;padding:14px;"
"box-shadow:0 4px 24px rgba(0,0,0,0.5);}\n"
".panel h3{font-size:12px;font-weight:700;letter-spacing:3px;color:var(--accent);text-transform:uppercase;"
"margin-bottom:12px;padding-bottom:8px;border-bottom:1px solid var(--border);}\n"
/* Sensor bars */
".sensor-row{display:flex;align-items:center;gap:8px;margin:6px 0;font-family:'Share Tech Mono';font-size:12px;}\n"
".sl{width:56px;color:var(--dim);}\n"
".sb-wrap{flex:1;height:8px;background:rgba(255,255,255,0.06);border-radius:4px;overflow:hidden;}\n"
".sb{height:100%;width:0%;border-radius:4px;transition:width 0.25s,background 0.25s;background:var(--accent3);}\n"
".sb.danger{background:var(--accent2);}\n"
".sv{width:50px;text-align:right;color:var(--text);}\n"
/* Radar circles */
".rw{display:flex;justify-content:center;gap:18px;margin:8px 0;}\n"
".rc{width:70px;height:70px;border-radius:50%;border:2px solid var(--border);"
"display:flex;flex-direction:column;align-items:center;justify-content:center;"
"font-family:'Share Tech Mono';font-size:10px;transition:border-color 0.25s,box-shadow 0.25s;}\n"
".rc .rcl{font-size:9px;color:var(--dim);letter-spacing:1px;}\n"
".rc .rcv{font-size:15px;font-weight:700;color:var(--accent3);}\n"
".rc.blocked{border-color:var(--accent2);box-shadow:0 0 14px rgba(255,75,43,0.5);}\n"
".rc.blocked .rcv{color:var(--accent2);}\n"
/* Status items */
".si{display:flex;justify-content:space-between;align-items:center;padding:5px 0;"
"border-bottom:1px solid rgba(255,255,255,0.04);font-size:13px;}\n"
".si:last-child{border-bottom:none;}\n"
".sk{color:var(--dim);font-size:11px;letter-spacing:1px;text-transform:uppercase;}\n"
".sv2{font-family:'Share Tech Mono';font-size:12px;}\n"
".ok{color:var(--accent3);}.warn2{color:var(--warn);font-weight:700;}\n"
".err{color:var(--accent2);font-weight:700;animation:blink 0.7s infinite;}\n"
".ram-on{color:var(--ram);font-weight:700;text-shadow:0 0 8px rgba(255,51,0,0.7);animation:blink 0.5s infinite;}\n"
"@keyframes blink{0%,100%{opacity:1}50%{opacity:0.3}}\n"
/* Buttons */
".btn{padding:9px 12px;margin:3px;font-family:'Rajdhani',sans-serif;font-size:12px;"
"font-weight:700;letter-spacing:1px;border:1px solid rgba(255,255,255,0.1);border-radius:8px;"
"cursor:pointer;transition:all 0.12s;text-transform:uppercase;user-select:none;"
"touch-action:manipulation;}\n"
".btn:active{transform:scale(0.95);}\n"
".btn.dir{background:rgba(0,200,255,0.1);color:var(--accent);border-color:rgba(0,200,255,0.3);}\n"
".btn.dir:hover{background:rgba(0,200,255,0.2);}\n"
".btn.stop-btn{background:rgba(255,75,43,0.12);color:var(--accent2);border-color:rgba(255,75,43,0.4);}\n"
".btn.stop-btn:hover{background:rgba(255,75,43,0.25);}\n"
".btn.tail{background:rgba(255,204,0,0.1);color:var(--warn);border-color:rgba(255,204,0,0.3);}\n"
".btn.rst{background:rgba(0,255,136,0.1);color:var(--accent3);border-color:rgba(0,255,136,0.3);}\n"
".btn.active{box-shadow:0 0 14px rgba(0,200,255,0.6);background:rgba(0,200,255,0.22);}\n"
".btn.ram-off{background:rgba(255,51,0,0.08);color:var(--ram);border-color:rgba(255,51,0,0.4);font-size:11px;}\n"
".btn.ram-on-btn{background:rgba(255,51,0,0.3);color:#fff;border-color:var(--ram);"
"box-shadow:0 0 16px rgba(255,51,0,0.7);animation:rampulse 0.8s infinite;}\n"
"@keyframes rampulse{0%,100%{box-shadow:0 0 16px rgba(255,51,0,0.7)}50%{box-shadow:0 0 30px rgba(255,51,0,1)}}\n"
/* Banners */
"#alertBanner{display:none;margin:0 12px 8px;padding:10px 14px;border-radius:8px;"
"background:rgba(255,75,43,0.15);border:1px solid rgba(255,75,43,0.6);color:var(--accent2);"
"font-weight:700;font-size:13px;letter-spacing:1px;text-align:center;animation:blink 0.7s infinite;}\n"
"#obsBanner{display:none;margin:0 12px 8px;padding:8px 14px;border-radius:8px;"
"background:rgba(255,204,0,0.12);border:1px solid rgba(255,204,0,0.5);"
"color:var(--warn);font-weight:700;font-size:12px;text-align:center;}\n"
/* Joystick */
".jw{display:flex;justify-content:center;margin:8px 0;}\n"
".joystick{width:148px;height:148px;border-radius:50%;"
"background:radial-gradient(circle at 30% 30%,#1a2030 0,#050810 60%);"
"border:1px solid var(--border);position:relative;"
"box-shadow:0 8px 20px rgba(0,0,0,0.8),0 0 20px rgba(0,200,255,0.07) inset;"
"touch-action:none;}\n"
".joy-h{width:52px;height:52px;border-radius:50%;"
"background:radial-gradient(circle at 30% 30%,#3a4a60 0,#1a2030 40%,#080c14 100%);"
"position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);"
"box-shadow:0 0 10px rgba(0,200,255,0.25),0 4px 8px rgba(0,0,0,0.8);"
"transition:left 0.04s,top 0.04s;pointer-events:none;}\n"
".jlbl{font-size:10px;color:var(--dim);text-align:center;margin-top:4px;letter-spacing:1px;}\n"
/* Button grid */
".bgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:4px;margin-top:8px;}\n"
".bgrid .btn{padding:7px 3px;font-size:10px;min-width:unset;}\n"
/* LCD */
".lcd{background:#0a1a0a;border:2px solid #1a4a1a;border-radius:6px;padding:8px 12px;"
"font-family:'Share Tech Mono';font-size:13px;color:#44ff44;"
"text-shadow:0 0 6px rgba(0,255,0,0.6);box-shadow:0 0 10px rgba(0,100,0,0.4) inset;"
"letter-spacing:1px;margin-top:8px;}\n"
".ll{height:20px;white-space:pre;overflow:hidden;}\n"
".ld{border-top:1px solid #1a3a1a;margin:4px 0;}\n"
".full{grid-column:1/-1;}\n"
".brow{display:flex;flex-wrap:wrap;gap:4px;justify-content:center;margin-top:6px;}\n"
/* Ping dot */
"#pingDot{width:8px;height:8px;border-radius:50%;background:#444;display:inline-block;margin-left:6px;"
"transition:background 0.3s;}\n"
"#pingDot.ok{background:var(--accent3);box-shadow:0 0 6px var(--accent3);}\n"
"#pingDot.err{background:var(--accent2);}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"<div><h1>&#9889; ESP32 CAR <span id='pingDot'></span></h1></div>\n"
"<small>SSID: CarController &nbsp;|&nbsp; PWD: 12345678</small>\n"
"</header>\n"
"<div id='pingBar'></div>\n"
"<div id='alertBanner'>&#9888;&#65039; ACCIDENT DETECTED &mdash; MOVEMENT BLOCKED</div>\n"
"<div id='obsBanner'>&#128680; OBSTACLE DETECTED &mdash; AUTO STOPPED</div>\n"
"<div class='grid'>\n"

/* === JOYSTICK PANEL === */
"<div class='panel'>\n"
"<h3>&#128579; Joystick</h3>\n"
"<div class='jw'><div class='joystick' id='joy'><div class='joy-h' id='joyH'></div></div></div>\n"
"<div class='jlbl'>DRAG TO DRIVE &bull; RELEASE = STOP</div>\n"
"<div class='bgrid'>\n"
"<button class='btn dir' id='bDL'  onpointerdown=\"mv('drift_left')\">DFT-L</button>\n"
"<button class='btn dir' id='bFWD' onpointerdown=\"mv('forward')\">&#9650; FWD</button>\n"
"<button class='btn dir' id='bDR'  onpointerdown=\"mv('drift_right')\">DFT-R</button>\n"
"<button class='btn dir' id='bL'   onpointerdown=\"mv('left')\">&#9668; LEFT</button>\n"
"<button class='btn stop-btn' id='bSTOP' onpointerdown=\"mv('stop')\">&#9632; STOP</button>\n"
"<button class='btn dir' id='bR'   onpointerdown=\"mv('right')\">RIGHT &#9658;</button>\n"
"<div></div>\n"
"<button class='btn dir' id='bBWD' onpointerdown=\"mv('backward')\">&#9660; BWD</button>\n"
"<div></div>\n"
"</div></div>\n"

/* === SENSORS PANEL === */
"<div class='panel'>\n"
"<h3>&#128225; Ultrasonic</h3>\n"
"<div class='rw'>\n"
"<div class='rc' id='rcF'><span class='rcl'>FRONT</span><span class='rcv' id='rcFv'>---</span><span class='rcl'>cm</span></div>\n"
"<div class='rc' id='rcB'><span class='rcl'>BACK</span><span class='rcv' id='rcBv'>---</span><span class='rcl'>cm</span></div>\n"
"</div>\n"
"<div class='sensor-row'><span class='sl'>FRONT</span><div class='sb-wrap'><div class='sb' id='sbF'></div></div><span class='sv' id='svF'>--- cm</span></div>\n"
"<div class='sensor-row'><span class='sl'>BACK</span><div class='sb-wrap'><div class='sb' id='sbB'></div></div><span class='sv' id='svB'>--- cm</span></div>\n"
"<div class='lcd'><div class='ll' id='l1'>Dir: STOP       </div><div class='ld'></div><div class='ll' id='l2'>F:--- B:---     </div></div>\n"
"</div>\n"

/* === LIGHTS & SAFETY PANEL === */
"<div class='panel'>\n"
"<h3>&#128161; Lights &amp; Safety</h3>\n"
"<div class='brow'>\n"
"<button class='btn tail' onclick=\"setTail(1)\">TAIL ON</button>\n"
"<button class='btn tail' onclick=\"setTail(0)\">TAIL OFF</button>\n"
"<button class='btn rst'  onclick='resetAcc()'>RESET ACCIDENT</button>\n"
"</div>\n"
"<div style='margin-top:12px;padding-top:10px;border-top:1px solid var(--border);'>\n"
"<div style='font-size:10px;color:var(--dim);letter-spacing:2px;margin-bottom:8px;'>&#9888; DANGER ZONE</div>\n"
"<button class='btn ram-off' id='bRAM' onclick='toggleRam()'>&#128165; RAMMING MODE: OFF</button>\n"
"<div style='font-size:10px;color:var(--dim);margin-top:6px;line-height:1.5;'>Bypasses obstacle avoidance.<br>Accident detection still active.</div>\n"
"</div></div>\n"

/* === STATUS PANEL === */
"<div class='panel'>\n"
"<h3>&#128202; Status</h3>\n"
"<div class='si'><span class='sk'>Direction</span><span class='sv2' id='sDir'>&mdash;</span></div>\n"
"<div class='si'><span class='sk'>Tail Light</span><span class='sv2' id='sTail'>&mdash;</span></div>\n"
"<div class='si'><span class='sk'>Accident</span><span class='sv2' id='sAcc'>&mdash;</span></div>\n"
"<div class='si'><span class='sk'>Vibration</span><span class='sv2' id='sVib'>&mdash;</span></div>\n"
"<div class='si'><span class='sk'>Front Obs.</span><span class='sv2' id='sFObs'>&mdash;</span></div>\n"
"<div class='si'><span class='sk'>Back Obs.</span><span class='sv2' id='sBObs'>&mdash;</span></div>\n"
"<div class='si'><span class='sk'>Ramming</span><span class='sv2' id='sRam'>&mdash;</span></div>\n"
"<div class='si'><span class='sk'>Ping</span><span class='sv2' id='sPing'>&mdash;</span></div>\n"
"</div>\n"

"</div>\n" /* end .grid */

/* ===================== JAVASCRIPT ===================== */
"<script>\n"

/* --- State --- */
"var lastAcc=0,lastFB=0,lastBB=0,ramOn=0;\n"
"var lastCmd='';\n"
"var inFlight=0;\n"     /* number of in-flight HTTP requests */
"var pendingCmd=null;\n" /* command waiting while a request is in flight */

/* --- Move command with request serialisation --- */
/* Only ONE /move request in flight at a time.
   If a new command arrives while busy, it overwrites pendingCmd.
   When request completes, pendingCmd is dispatched if set. */
"function mv(dir){\n"
"  if(dir===lastCmd && dir!=='stop') return;\n" /* deduplicate same-direction spam */
"  if(inFlight>0){pendingCmd=dir;return;}\n"
"  sendMove(dir);\n"
"}\n"

"function sendMove(dir){\n"
"  lastCmd=dir;\n"
"  inFlight++;\n"
"  hiBtn(dir);\n"
"  var t0=Date.now();\n"
"  fetch('/move?dir='+dir,{method:'GET',keepalive:true})\n"
"    .then(function(r){return r.text();})\n"
"    .then(function(){inFlight--;flushPending();})\n"
"    .catch(function(){inFlight--;flushPending();});\n"
"}\n"

"function flushPending(){\n"
"  if(pendingCmd!==null){var c=pendingCmd;pendingCmd=null;sendMove(c);}\n"
"}\n"

"function hiBtn(dir){\n"
"  var map={forward:'bFWD',backward:'bBWD',left:'bL',right:'bR',drift_left:'bDL',drift_right:'bDR',stop:'bSTOP'};\n"
"  ['bFWD','bBWD','bL','bR','bDL','bDR','bSTOP'].forEach(function(id){\n"
"    var el=document.getElementById(id);if(el)el.classList.remove('active');\n"
"  });\n"
"  var id=map[dir];if(id){var el=document.getElementById(id);if(el)el.classList.add('active');}\n"
"}\n"

"function setTail(s){fetch('/tail?state='+(s?'on':'off')).catch(function(){});}\n"
"function resetAcc(){fetch('/reset_accident').catch(function(){});}\n"

"function toggleRam(){\n"
"  ramOn=!ramOn;\n"
"  fetch('/ramming?state='+(ramOn?'on':'off')).catch(function(){});\n"
"  updateRamUI();\n"
"}\n"
"function updateRamUI(){\n"
"  var b=document.getElementById('bRAM');\n"
"  var s=document.getElementById('sRam');\n"
"  if(ramOn){b.textContent='RAMMING MODE: ON';b.className='btn ram-on-btn';\n"
"    s.textContent='ENABLED';s.className='sv2 ram-on';}\n"
"  else{b.textContent='RAMMING MODE: OFF';b.className='btn ram-off';\n"
"    s.textContent='DISABLED';s.className='sv2 ok';}\n"
"}\n"

"function updateBar(bid,vid,rcId,rcVid,dist){\n"
"  var pct=Math.min(100,Math.round(dist/100*100));\n"
"  var bl=dist<20;\n"
"  var b=document.getElementById(bid);if(b){b.style.width=pct+'%';b.className='sb'+(bl?' danger':'');}\n"
"  var v=document.getElementById(vid);if(v)v.textContent=dist<500?dist+' cm':'-- cm';\n"
"  var rc=document.getElementById(rcId);if(rc)rc.className='rc'+(bl?' blocked':'');\n"
"  var rv=document.getElementById(rcVid);if(rv)rv.textContent=dist<500?dist:'--';\n"
"}\n"

/* Status poll at 500ms */
"function pollStatus(){\n"
"  var t0=Date.now();\n"
"  fetch('/status')\n"
"    .then(function(r){return r.json();})\n"
"    .then(function(d){\n"
"      var ping=Date.now()-t0;\n"
"      document.getElementById('sPing').textContent=ping+' ms';\n"
"      var pd=document.getElementById('pingDot');\n"
"      pd.className=ping<300?'ok':'err';\n"
"      document.getElementById('sDir').textContent=d.direction;\n"
"      document.getElementById('sTail').textContent=d.tail?'ON':'OFF';\n"
"      document.getElementById('sVib').textContent=d.vib;\n"
"      var as=document.getElementById('sAcc');\n"
"      if(d.accident){as.textContent='DETECTED!';as.className='sv2 err';\n"
"        document.getElementById('alertBanner').style.display='block';\n"
"        if(!lastAcc)alert('ACCIDENT DETECTED!\\n\\nLocation: 28deg28 N 77deg28 E\\nVibration: '+d.vib+'\\n\\nMovement blocked.');\n"
"      }else{as.textContent='OK';as.className='sv2 ok';\n"
"        document.getElementById('alertBanner').style.display='none';}\n"
"      lastAcc=d.accident?1:0;\n"
"      updateBar('sbF','svF','rcF','rcFv',d.front_dist);\n"
"      updateBar('sbB','svB','rcB','rcBv',d.back_dist);\n"
"      var fo=document.getElementById('sFObs');\n"
"      var bo=document.getElementById('sBObs');\n"
"      fo.textContent=d.front_blocked?(d.front_dist+' cm BLOCKED'):(d.front_dist<500?d.front_dist+' cm OK':'No Echo');\n"
"      fo.className='sv2 '+(d.front_blocked?'err':'ok');\n"
"      bo.textContent=d.back_blocked?(d.back_dist+' cm BLOCKED'):(d.back_dist<500?d.back_dist+' cm OK':'No Echo');\n"
"      bo.className='sv2 '+(d.back_blocked?'err':'ok');\n"
"      var obs=!d.ramming&&(d.front_blocked||d.back_blocked);\n"
"      document.getElementById('obsBanner').style.display=obs?'block':'none';\n"
"      if(!d.ramming){\n"
"        if(!lastFB&&d.front_blocked)alert('FRONT OBSTACLE!\\nDistance: '+d.front_dist+' cm\\nCar auto-stopped.');\n"
"        if(!lastBB&&d.back_blocked)alert('BACK OBSTACLE!\\nDistance: '+d.back_dist+' cm\\nCar auto-stopped.');\n"
"      }\n"
"      lastFB=d.front_blocked?1:0;\n"
"      lastBB=d.back_blocked?1:0;\n"
"      if(d.ramming!=(ramOn?1:0)){ramOn=d.ramming;updateRamUI();}\n"
"      var l1='Dir: '+(d.direction.substring(0,7)).padEnd(7)+(d.ramming?' RAM':'    ');\n"
"      var l2;\n"
"      if(d.accident)l2='!! ACCIDENT !!  ';\n"
"      else if(d.front_blocked&&d.back_blocked)l2='F&B BLOCKED     ';\n"
"      else if(d.front_blocked)l2='F:'+d.front_dist+'cm BLK    ';\n"
"      else if(d.back_blocked)l2='B:'+d.back_dist+'cm BLK    ';\n"
"      else l2='F:'+(d.front_dist<500?d.front_dist:'---')+' B:'+(d.back_dist<500?d.back_dist:'---')+'      ';\n"
"      document.getElementById('l1').textContent=l1.padEnd(16).substring(0,16);\n"
"      document.getElementById('l2').textContent=l2.padEnd(16).substring(0,16);\n"
"    })\n"
"    .catch(function(){document.getElementById('pingDot').className='err';});\n"
"}\n"
"setInterval(pollStatus,500);\n"

/* ===== JOYSTICK ===== */
"(function(){\n"
"var joy=document.getElementById('joy');\n"
"var joyH=document.getElementById('joyH');\n"
"var JR=55,DEAD=12;\n"
"var active=false,cx=0,cy=0,lastJoyCmd='';\n"

"function setH(dx,dy){\n"
"  var pct=34;\n"
"  joyH.style.left=(50+(dx/JR)*pct)+'%';\n"
"  joyH.style.top=(50+(dy/JR)*pct)+'%';\n"
"}\n"

"function vecToCmd(dx,dy){\n"
"  var fy=-dy;\n"
"  var mag=Math.sqrt(dx*dx+fy*fy);\n"
"  if(mag<DEAD)return 'stop';\n"
"  var a=Math.atan2(fy,dx)*180/Math.PI;\n"
"  if(a>65&&a<115)return 'forward';\n"
"  if(a<-65&&a>-115)return 'backward';\n"
"  if(a>=115||a<=-115)return 'left';\n"
"  if(a>=-30&&a<=30)return 'right';\n"
"  if(a>30&&a<=65)return 'drift_right';\n"
"  if(a>115&&a<=150)return 'drift_left';\n"
"  if(a<-30&&a>=-65)return 'drift_right';\n"
"  if(a<=-150||a>=150)return 'drift_left';\n"
"  return 'stop';\n"
"}\n"

"function onStart(e){\n"
"  e.preventDefault();active=true;\n"
"  var r=joy.getBoundingClientRect();\n"
"  cx=r.left+r.width/2;cy=r.top+r.height/2;\n"
"  if(joy.setPointerCapture&&e.pointerId)joy.setPointerCapture(e.pointerId);\n"
"}\n"

"function onMove(e){\n"
"  if(!active)return;e.preventDefault();\n"
"  var t=e.touches?e.touches[0]:e;\n"
"  var dx=t.clientX-cx,dy=t.clientY-cy;\n"
"  var m=Math.sqrt(dx*dx+dy*dy);\n"
"  if(m>JR){dx=dx*JR/m;dy=dy*JR/m;}\n"
"  setH(dx,dy);\n"
"  var cmd=vecToCmd(dx,dy);\n"
"  if(cmd!==lastJoyCmd){lastJoyCmd=cmd;mv(cmd);}\n"
"}\n"

"function onEnd(e){\n"
"  e.preventDefault();active=false;lastJoyCmd='stop';\n"
"  setH(0,0);mv('stop');\n"
"}\n"

"joy.addEventListener('pointerdown',onStart,{passive:false});\n"
"joy.addEventListener('pointermove',onMove,{passive:false});\n"
"joy.addEventListener('pointerup',onEnd,{passive:false});\n"
"joy.addEventListener('pointercancel',onEnd,{passive:false});\n"
"joy.addEventListener('touchstart',onStart,{passive:false});\n"
"joy.addEventListener('touchmove',onMove,{passive:false});\n"
"joy.addEventListener('touchend',onEnd,{passive:false});\n"
"document.addEventListener('mouseup',onEnd,{passive:false});\n"
"})();\n"

"window.addEventListener('load',function(){updateRamUI();pollStatus();});\n"
"</script>\n"
"</body></html>\n";

const char *html_get_page(void)
{
    return HTML_PAGE;
}