/*
 * html_page.c — Solar Panel Cleaner Dashboard v3.1-fixed
 *
 * BUG FIXES vs v3.0:
 *  - Removed all <!-- --> HTML comments from inside <script> blocks
 *    (they break JavaScript parsing in all browsers)
 *  - Replaced confirm() calls with custom modal dialogs
 *    (confirm() is blocked in sandboxed/cross-origin iframes)
 *  - Fixed IIFE scope: joystick IIFE closing })() was misplaced,
 *    it was wrapping drawGrid/loadGrid inside the IIFE making them
 *    unreachable from onclick handlers
 *  - Fixed calcGrid() call in drawGrid — was passing d.rgap but
 *    the object key is d.rgap (set by calcGrid as rgap:rgap) — OK now
 *  - Added rover_w_cm / rover_d_cm to sensor_check JSON fields used in UI
 *  - All event handlers verified to be in global scope
 */

#include "html_page.h"

static const char HTML_PAGE[] =

"<!DOCTYPE html>"
"<html lang='en'>"
"<head>"
"<meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no'>"
"<title>SolarBot v3</title>"
"<link href='https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;500;600;700&family=Share+Tech+Mono&display=swap' rel='stylesheet'>"
"<style>"
":root{"
"--bg:#0a0c0e;--s1:#0f1318;--s2:#141920;--s3:#1c2430;"
"--bdr:rgba(255,180,0,0.12);--bdr2:rgba(255,180,0,0.25);"
"--acc:#ffb400;--acc2:#ff4500;--acc3:#00e5ff;--acc4:#39ff14;"
"--text:#d0c8a0;--dim:#5a5438;--dim2:#8a8060;"
"--ok:#39ff14;--warn:#ffb400;--err:#ff4500;--info:#00e5ff;"
"--pump:#00cfff;--blow:#ff7700;"
"--rec:#ff2255;--servo:#a855f7;"
"--r:8px;"
"}"
"*{box-sizing:border-box;margin:0;padding:0;-webkit-tap-highlight-color:transparent;}"
"html{scroll-behavior:smooth;}"
"body{"
"font-family:'Rajdhani',sans-serif;"
"background:var(--bg);"
"color:var(--text);"
"min-height:100vh;"
"background-image:"
"  radial-gradient(ellipse 80% 50% at 50% -10%,rgba(255,180,0,0.06) 0%,transparent 60%),"
"  repeating-linear-gradient(0deg,transparent,transparent 47px,rgba(255,180,0,0.018) 48px),"
"  repeating-linear-gradient(90deg,transparent,transparent 47px,rgba(255,180,0,0.018) 48px);"
"}"
"header{"
"padding:0 20px;"
"height:52px;"
"background:rgba(0,0,0,0.9);"
"border-bottom:2px solid var(--acc);"
"display:flex;align-items:center;justify-content:space-between;"
"position:sticky;top:0;z-index:50;"
"box-shadow:0 0 30px rgba(255,180,0,0.15);"
"}"
"header .logo{"
"font-size:18px;font-weight:700;letter-spacing:4px;"
"color:var(--acc);text-transform:uppercase;"
"text-shadow:0 0 20px rgba(255,180,0,0.5);"
"}"
"header .logo span{color:var(--dim2);font-weight:400;font-size:11px;margin-left:8px;letter-spacing:2px;}"
"#connDot{"
"width:10px;height:10px;border-radius:50%;display:inline-block;"
"background:#333;margin-left:8px;transition:all 0.4s;"
"}"
"#connDot.ok{background:var(--ok);box-shadow:0 0 10px var(--ok);}"
"#connDot.err{background:var(--err);box-shadow:0 0 10px var(--err);}"

/* Modal overlay */
".modal-overlay{"
"display:none;position:fixed;inset:0;background:rgba(0,0,0,0.75);"
"z-index:1000;align-items:center;justify-content:center;"
"}"
".modal-overlay.show{display:flex;}"
".modal-box{"
"background:var(--s2);border:1px solid var(--bdr2);border-radius:10px;"
"padding:24px;max-width:360px;width:90%;text-align:center;"
"}"
".modal-box p{"
"font-family:'Share Tech Mono';font-size:12px;color:var(--text);"
"line-height:1.7;margin-bottom:18px;"
"}"
".modal-btns{display:flex;gap:10px;justify-content:center;}"

/* Toast */
"#toastWrap{position:fixed;top:58px;right:14px;z-index:999;display:flex;flex-direction:column;gap:5px;pointer-events:none;}"
".toast{"
"padding:7px 14px;border-radius:5px;"
"font-family:'Share Tech Mono';font-size:11px;letter-spacing:1px;"
"border:1px solid;pointer-events:none;"
"animation:tIn 0.18s ease,tOut 0.3s ease 3.7s forwards;"
"}"
".toast.ok{background:rgba(57,255,20,0.12);border-color:rgba(57,255,20,0.4);color:var(--ok);}"
".toast.warn{background:rgba(255,180,0,0.12);border-color:rgba(255,180,0,0.4);color:var(--warn);}"
".toast.err{background:rgba(255,69,0,0.15);border-color:rgba(255,69,0,0.5);color:var(--err);}"
".toast.rec{background:rgba(255,34,85,0.15);border-color:rgba(255,34,85,0.5);color:var(--rec);}"
".toast.info{background:rgba(0,229,255,0.1);border-color:rgba(0,229,255,0.35);color:var(--info);}"
"@keyframes tIn{from{opacity:0;transform:translateX(16px)}to{opacity:1;transform:none}}"
"@keyframes tOut{to{opacity:0}}"

/* Banners */
".banner{"
"margin:8px 12px;padding:8px 16px;border-radius:6px;"
"font-family:'Share Tech Mono';font-size:11px;font-weight:600;text-align:center;letter-spacing:1px;"
"}"
"#obsBanner{display:none;background:rgba(255,180,0,0.1);border:1px solid rgba(255,180,0,0.5);color:var(--warn);animation:blink 0.9s infinite;}"
"#recBanner{display:none;background:rgba(255,34,85,0.08);border:1px solid rgba(255,34,85,0.4);color:var(--rec);animation:blink 0.7s infinite;}"
"#pauseBanner{display:none;background:rgba(0,229,255,0.08);border:1px solid rgba(0,229,255,0.3);color:var(--info);}"
"@keyframes blink{0%,100%{opacity:1}50%{opacity:.4}}"

/* Layout */
".pg{display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:12px;max-width:1200px;margin:0 auto;}"
"@media(max-width:680px){.pg{grid-template-columns:1fr;}}"
".fc{grid-column:1/-1;}"

/* Card */
".card{"
"background:var(--s1);"
"border:1px solid var(--bdr);"
"border-radius:var(--r);"
"padding:16px;"
"position:relative;overflow:hidden;"
"}"
".card::before{"
"content:'';position:absolute;top:0;left:0;right:0;height:2px;"
"background:linear-gradient(90deg,transparent,var(--acc),transparent);"
"opacity:0.6;"
"}"
".card h3{"
"font-size:11px;font-weight:700;letter-spacing:3px;text-transform:uppercase;"
"color:var(--acc);margin-bottom:14px;"
"padding-bottom:8px;border-bottom:1px solid var(--bdr);"
"display:flex;align-items:center;gap:8px;"
"}"
".card h3 .ic{font-size:14px;}"

/* Status row */
".sr{display:flex;justify-content:space-between;align-items:center;padding:5px 0;"
"border-bottom:1px solid rgba(255,255,255,0.04);}"
".sr:last-child{border-bottom:none;}"
".sk{font-size:10px;letter-spacing:1px;color:var(--dim2);font-family:'Share Tech Mono';text-transform:uppercase;}"
".sv{font-family:'Share Tech Mono';font-size:11px;color:var(--text);}"
".sv.ok{color:var(--ok);}.sv.warn{color:var(--warn);font-weight:700;}"
".sv.err{color:var(--err);font-weight:700;}.sv.info{color:var(--info);}"
".sv.pump{color:var(--pump);font-weight:700;}.sv.blow{color:var(--blow);font-weight:700;}"
".sv.servo{color:var(--servo);font-weight:700;}"
".sv.rec-on{color:var(--rec);font-weight:700;animation:blink 0.8s infinite;}"

/* LCD */
".lcd{background:#050a04;border:1px solid #1e3a1a;border-radius:5px;padding:8px 12px;"
"font-family:'Share Tech Mono';font-size:12px;color:#44ff55;"
"text-shadow:0 0 8px rgba(68,255,85,0.6);"
"box-shadow:0 0 15px rgba(0,80,0,0.3) inset;letter-spacing:1px;margin-top:10px;}"
".ll{height:18px;white-space:pre;overflow:hidden;}"
".ld{border-top:1px solid #1a3a1a;margin:3px 0;}"

/* Buttons */
".btn{"
"display:inline-flex;align-items:center;justify-content:center;gap:4px;"
"padding:8px 12px;margin:2px;"
"font-family:'Rajdhani',sans-serif;font-size:11px;font-weight:700;letter-spacing:1px;"
"text-transform:uppercase;border-radius:5px;cursor:pointer;"
"border:1px solid rgba(255,255,255,0.1);"
"background:rgba(255,255,255,0.03);color:var(--text);"
"transition:all 0.1s;user-select:none;touch-action:manipulation;"
"}"
".btn:active{transform:scale(0.94);}"
".btn:disabled{opacity:0.3;cursor:not-allowed;}"
".btn.dir{background:rgba(255,180,0,0.07);color:var(--acc);border-color:rgba(255,180,0,0.25);}"
".btn.dir:active,.btn.dir.active{background:rgba(255,180,0,0.22);box-shadow:0 0 14px rgba(255,180,0,0.4);}"
".btn.stop-b{background:rgba(255,69,0,0.1);color:var(--err);border-color:rgba(255,69,0,0.35);}"
".btn.ok-b{background:rgba(57,255,20,0.08);color:var(--ok);border-color:rgba(57,255,20,0.3);}"
".btn.info-b{background:rgba(0,229,255,0.07);color:var(--info);border-color:rgba(0,229,255,0.25);}"
".btn.warn-b{background:rgba(255,180,0,0.1);color:var(--warn);border-color:rgba(255,180,0,0.3);}"
".btn.rec-b{background:rgba(255,34,85,0.1);color:var(--rec);border-color:rgba(255,34,85,0.35);}"
".btn.servo-b{background:rgba(168,85,247,0.1);color:var(--servo);border-color:rgba(168,85,247,0.35);}"
".btn.full{width:100%;margin:3px 0;padding:10px;letter-spacing:2px;}"
".btn.xl{padding:12px;font-size:13px;}"

/* Drive grid */
".dg{display:grid;grid-template-columns:repeat(3,1fr);gap:4px;margin-top:8px;}"
".dg .btn{padding:7px 4px;font-size:10px;}"

/* Joystick */
".jw{display:flex;justify-content:center;margin:10px 0;}"
".joy{"
"width:140px;height:140px;border-radius:50%;"
"background:radial-gradient(circle at 35% 35%,#1a1408 0,#060504 70%);"
"border:2px solid var(--bdr2);"
"position:relative;"
"box-shadow:0 6px 20px rgba(0,0,0,0.7),0 0 20px rgba(255,180,0,0.04) inset;"
"touch-action:none;"
"}"
".joy-h{"
"width:44px;height:44px;border-radius:50%;"
"background:radial-gradient(circle at 35% 35%,#3a2800 0,#1a1000 70%);"
"border:2px solid rgba(255,180,0,0.5);"
"position:absolute;left:50%;top:50%;"
"transform:translate(-50%,-50%);"
"box-shadow:0 0 12px rgba(255,180,0,0.25);"
"transition:left 0.04s,top 0.04s;pointer-events:none;"
"}"
".jlbl{text-align:center;font-size:9px;color:var(--dim2);letter-spacing:2px;margin-top:4px;}"

/* Peripheral row */
".prow{display:flex;gap:8px;margin-top:10px;padding-top:10px;border-top:1px solid var(--bdr);}"
".pbtn{flex:1;padding:10px 4px;border-radius:6px;border:1px solid;cursor:pointer;"
"font-family:'Rajdhani',sans-serif;font-size:10px;font-weight:700;letter-spacing:1px;"
"text-align:center;transition:all 0.15s;text-transform:uppercase;}"
".pb-pump{background:rgba(0,207,255,0.06);color:var(--pump);border-color:rgba(0,207,255,0.25);}"
".pb-pump.on{background:rgba(0,207,255,0.2);box-shadow:0 0 16px rgba(0,207,255,0.35);}"
".pb-blow{background:rgba(255,119,0,0.06);color:var(--blow);border-color:rgba(255,119,0,0.25);}"
".pb-blow.on{background:rgba(255,119,0,0.2);box-shadow:0 0 16px rgba(255,119,0,0.35);}"

/* IR grid */
".ir-g{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:6px;}"
".ir-c{border:1px solid var(--bdr);border-radius:6px;padding:10px;text-align:center;transition:all 0.25s;}"
".ir-c .lbl{font-size:8px;color:var(--dim2);letter-spacing:2px;margin-bottom:6px;}"
".ir-c .dot{width:26px;height:26px;border-radius:50%;margin:0 auto 6px;border:2px solid var(--s3);transition:all 0.2s;}"
".ir-c .st{font-family:'Share Tech Mono';font-size:10px;color:var(--dim2);}"
".ir-c.clear .dot{background:rgba(57,255,20,0.2);border-color:var(--ok);box-shadow:0 0 10px rgba(57,255,20,0.4);}"
".ir-c.clear .st{color:var(--ok);}"
".ir-c.blocked .dot{background:rgba(255,69,0,0.3);border-color:var(--err);box-shadow:0 0 14px rgba(255,69,0,0.6);}"
".ir-c.blocked .st{color:var(--err);font-weight:700;}"
".zone-row{display:flex;justify-content:space-between;margin-top:10px;padding-top:10px;"
"border-top:1px solid var(--bdr);font-family:'Share Tech Mono';font-size:9px;}"
".zone{text-align:center;}"
".zl{color:var(--dim2);letter-spacing:1px;margin-bottom:3px;}"
".zv{font-size:12px;font-weight:700;}"

/* MPU / compass */
".mpu-badge{display:inline-block;padding:3px 10px;border-radius:10px;font-size:9px;letter-spacing:2px;margin-bottom:10px;}"
".mpu-badge.ok{background:rgba(57,255,20,0.12);border:1px solid rgba(57,255,20,0.3);color:var(--ok);}"
".mpu-badge.fail{background:rgba(255,69,0,0.12);border:1px solid rgba(255,69,0,0.3);color:var(--err);}"
".imu-row{display:grid;grid-template-columns:auto auto 1fr;gap:12px;align-items:start;margin-top:8px;}"
".compass{position:relative;width:80px;height:80px;border-radius:50%;"
"background:radial-gradient(circle,#0d1208 0,#040601 100%);"
"border:2px solid rgba(255,180,0,0.25);flex-shrink:0;}"
".c-ring{position:absolute;inset:6px;border-radius:50%;border:1px solid rgba(255,180,0,0.1);}"
".c-n{position:absolute;top:3px;left:50%;transform:translateX(-50%);font-size:8px;color:var(--err);font-weight:700;}"
".c-s{position:absolute;bottom:3px;left:50%;transform:translateX(-50%);font-size:7px;color:var(--dim);}"
".c-e{position:absolute;right:3px;top:50%;transform:translateY(-50%);font-size:7px;color:var(--dim);}"
".c-w{position:absolute;left:3px;top:50%;transform:translateY(-50%);font-size:7px;color:var(--dim);}"
".c-needle{position:absolute;left:50%;top:50%;width:2px;height:28px;margin-left:-1px;margin-top:-28px;"
"background:linear-gradient(var(--err) 0%,transparent 100%);"
"transform-origin:bottom center;border-radius:2px 2px 0 0;transition:transform 0.12s linear;}"
".c-dot{position:absolute;left:50%;top:50%;width:6px;height:6px;border-radius:50%;"
"background:var(--acc);transform:translate(-50%,-50%);box-shadow:0 0 6px var(--acc);}"
".c-hdg{font-family:'Share Tech Mono';font-size:13px;color:var(--acc);text-align:center;margin-top:4px;}"
".tilt{position:relative;width:72px;height:72px;border-radius:50%;"
"background:radial-gradient(circle,#080d18 0,#030508 100%);"
"border:2px solid rgba(0,229,255,0.2);flex-shrink:0;overflow:hidden;}"
".t-ch{position:absolute;left:0;right:0;top:50%;height:1px;background:rgba(0,229,255,0.12);}"
".t-cv{position:absolute;top:0;bottom:0;left:50%;width:1px;background:rgba(0,229,255,0.12);}"
".t-ring{position:absolute;inset:16px;border-radius:50%;border:1px solid rgba(0,229,255,0.15);}"
".t-bub{position:absolute;width:12px;height:12px;border-radius:50%;"
"background:radial-gradient(circle at 35% 35%,rgba(0,229,255,0.9),rgba(0,120,200,0.5));"
"border:1px solid rgba(0,229,255,0.8);box-shadow:0 0 8px rgba(0,229,255,0.5);"
"left:50%;top:50%;transform:translate(-50%,-50%);transition:left 0.12s,top 0.12s;}"
".mpu-stats{flex:1;}"
".ab-row{display:flex;align-items:center;gap:5px;margin:3px 0;}"
".ab-ax{font-family:'Share Tech Mono';font-size:9px;color:var(--dim2);width:12px;text-align:right;}"
".ab-tr{flex:1;height:5px;background:rgba(255,255,255,0.05);border-radius:3px;overflow:hidden;position:relative;}"
".ab-cn{position:absolute;left:50%;top:0;bottom:0;width:1px;background:rgba(255,255,255,0.12);}"
".ab-fl{position:absolute;height:100%;border-radius:3px;transition:left 0.12s,width 0.12s;}"
".ab-fl.x{background:rgba(255,69,0,0.7);}.ab-fl.y{background:rgba(57,255,20,0.7);}.ab-fl.z{background:rgba(0,229,255,0.7);}"
".ab-val{font-family:'Share Tech Mono';font-size:9px;color:var(--text);width:44px;text-align:right;}"
".hdg-dev{margin-top:8px;}"
".hdg-track{height:8px;background:rgba(255,255,255,0.05);border-radius:4px;overflow:hidden;position:relative;}"
".hdg-center{position:absolute;left:50%;top:0;bottom:0;width:1px;background:rgba(255,180,0,0.3);}"
".hdg-bar{position:absolute;height:100%;background:var(--acc);border-radius:4px;transition:all 0.12s;}"
".hdg-labels{display:flex;justify-content:space-between;font-family:'Share Tech Mono';font-size:8px;color:var(--dim2);margin-top:2px;}"
".vib-wrap{margin-top:8px;}"
".vib-track{height:8px;background:rgba(255,255,255,0.05);border-radius:4px;overflow:hidden;}"
".vib-fill{height:100%;border-radius:4px;transition:width 0.2s,background 0.2s;}"

/* Servo panel */
".servo-arc-wrap{display:flex;flex-direction:column;align-items:center;margin-bottom:12px;}"
".servo-arc{position:relative;width:120px;height:70px;overflow:hidden;margin-bottom:4px;}"
".servo-arc svg{position:absolute;bottom:0;left:50%;transform:translateX(-50%);}"
".servo-angle-lbl{font-family:'Share Tech Mono';font-size:16px;color:var(--servo);font-weight:700;}"
".servo-pos-lbl{font-size:9px;color:var(--dim2);letter-spacing:2px;}"
".servo-btns{display:flex;gap:6px;flex-wrap:wrap;justify-content:center;margin:8px 0;}"
".angle-slider{"
"width:100%;-webkit-appearance:none;appearance:none;"
"height:6px;background:var(--s3);border-radius:3px;outline:none;margin:6px 0;"
"}"
".angle-slider::-webkit-slider-thumb{"
"-webkit-appearance:none;width:18px;height:18px;border-radius:50%;"
"background:var(--servo);border:2px solid var(--s1);"
"box-shadow:0 0 8px rgba(168,85,247,0.5);cursor:pointer;"
"}"

/* Speed slider */
".spd-row{display:flex;align-items:center;gap:10px;margin-top:8px;}"
".spd-slider{"
"flex:1;-webkit-appearance:none;appearance:none;"
"height:6px;background:var(--s3);border-radius:3px;outline:none;"
"}"
".spd-slider::-webkit-slider-thumb{"
"-webkit-appearance:none;width:18px;height:18px;border-radius:50%;"
"background:var(--acc);border:2px solid var(--s1);"
"box-shadow:0 0 8px rgba(255,180,0,0.4);cursor:pointer;"
"}"
".spd-lbl{font-family:'Share Tech Mono';font-size:12px;color:var(--acc);width:30px;text-align:right;}"

/* Auto-clean box */
".auto-box{background:var(--s2);border:1px solid var(--bdr);border-radius:6px;padding:14px;margin-top:12px;}"
".auto-state{font-size:12px;font-weight:700;letter-spacing:3px;margin-bottom:10px;}"
".auto-state.idle{color:var(--dim2);}"
".auto-state.running{color:var(--acc);animation:blink 1.5s infinite;}"
".auto-state.done{color:var(--ok);}"
".auto-state.paused{color:var(--info);}"
".auto-state.error{color:var(--err);}"
".prog-track{height:14px;background:rgba(255,255,255,0.04);border-radius:7px;overflow:hidden;margin:8px 0;position:relative;}"
".prog-fill{height:100%;border-radius:7px;background:linear-gradient(90deg,#a05000,var(--acc));transition:width 0.5s;}"
".prog-fill.done{background:linear-gradient(90deg,#007a20,var(--ok));}"
".prog-labels{display:flex;justify-content:space-between;font-family:'Share Tech Mono';font-size:9px;color:var(--dim2);}"
".panel-tracker{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px;}"
".pt-item{padding:3px 8px;border-radius:4px;font-size:9px;font-family:'Share Tech Mono';letter-spacing:1px;}"
".pt-done{background:rgba(57,255,20,0.12);border:1px solid rgba(57,255,20,0.25);color:var(--ok);}"
".pt-active{background:rgba(255,180,0,0.15);border:1px solid rgba(255,180,0,0.4);color:var(--acc);animation:blink 1.2s infinite;}"
".pt-pend{background:rgba(255,255,255,0.03);border:1px solid var(--bdr);color:var(--dim2);}"

/* Grid editor */
".ge-2{display:grid;grid-template-columns:1fr 1fr;gap:12px;}"
".ge-row{display:flex;align-items:center;gap:8px;margin:5px 0;}"
".ge-lbl{font-family:'Share Tech Mono';font-size:9px;color:var(--dim2);width:130px;letter-spacing:1px;}"
".ge-inp{"
"flex:1;background:var(--s2);border:1px solid var(--bdr);"
"border-radius:4px;color:var(--acc);font-family:'Share Tech Mono';font-size:12px;"
"padding:5px 8px;text-align:center;"
"}"
".ge-inp:focus{outline:none;border-color:var(--acc);box-shadow:0 0 8px rgba(255,180,0,0.2);}"
".chk-row{display:flex;align-items:center;gap:6px;cursor:pointer;font-size:11px;color:var(--dim2);margin:5px 0;}"
".chk-row input{accent-color:var(--acc);width:14px;height:14px;}"
"#calcInfo{"
"padding:10px;border-radius:5px;border:1px solid rgba(0,229,255,0.15);"
"background:rgba(0,229,255,0.04);"
"font-family:'Share Tech Mono';font-size:9px;line-height:2;color:var(--dim2);"
"margin-top:8px;"
"}"

/* Path panel */
".path-box{background:rgba(255,34,85,0.04);border:1px solid rgba(255,34,85,0.2);border-radius:6px;padding:12px;margin-top:10px;}"
".path-box h4{font-size:10px;letter-spacing:3px;color:var(--rec);text-transform:uppercase;margin-bottom:10px;}"
".path-status{font-family:'Share Tech Mono';font-size:10px;margin-bottom:8px;padding:6px 10px;"
"border-radius:5px;background:rgba(0,0,0,0.4);border:1px solid rgba(255,255,255,0.06);}"

/* Canvas */
"#gpCanvas{display:block;border-radius:4px;}"
"#gpInfo{font-family:'Share Tech Mono';font-size:9px;color:var(--dim2);margin-top:6px;line-height:1.8;}"

/* Sensor check table */
".chk-tbl{width:100%;border-collapse:collapse;font-family:'Share Tech Mono';font-size:10px;margin-top:8px;}"
".chk-tbl th{color:var(--dim2);font-size:8px;letter-spacing:2px;text-align:left;"
"padding:4px 6px;border-bottom:1px solid var(--bdr);}"
".chk-tbl td{padding:5px 6px;border-bottom:1px solid rgba(255,255,255,0.03);}"
".cok{color:var(--ok);}.cfail{color:var(--err);font-weight:700;}.cna{color:var(--dim2);}"

"</style>"
"</head>"
"<body>"

/* Modal dialog (replaces confirm()) */
"<div class='modal-overlay' id='modalOverlay'>"
"<div class='modal-box'>"
"<p id='modalMsg'>Are you sure?</p>"
"<div class='modal-btns'>"
"<button class='btn ok-b' id='modalOk'>YES</button>"
"<button class='btn stop-b' id='modalCancel'>CANCEL</button>"
"</div>"
"</div>"
"</div>"

"<div id='toastWrap'></div>"
"<header>"
"<div class='logo'>&#9728; SolarBot <span>v3.0</span> <span id='connDot'></span></div>"
"<div style='font-family:Share Tech Mono;font-size:9px;color:var(--dim2)'>SolarCleaner &nbsp;192.168.4.1</div>"
"</header>"

"<div class='banner' id='obsBanner'>&#9888; OBSTACLE DETECTED</div>"
"<div class='banner' id='recBanner'>&#9679; RECORDING — DRIVE ROVER NOW</div>"
"<div class='banner' id='pauseBanner'>&#9646;&#9646; AUTO-CLEAN PAUSED</div>"

"<div class='pg'>"

/* DRIVE PANEL */
"<div class='card'>"
"<h3><span class='ic'>&#127918;</span> Manual Drive"
" <span id='recInd' style='display:none;font-size:9px;color:var(--rec);animation:blink .8s infinite;margin-left:8px'>&#9679; REC</span></h3>"
"<div id='autoLock' style='display:none;margin-bottom:8px;padding:7px;border-radius:5px;"
"background:rgba(255,180,0,0.08);border:1px solid rgba(255,180,0,0.2);"
"font-family:Share Tech Mono;font-size:9px;color:var(--warn);text-align:center;'>&#9888; AUTO RUNNING — DRIVE LOCKED</div>"
"<div class='jw'><div class='joy' id='joy'><div class='joy-h' id='joyH'></div></div></div>"
"<div class='jlbl'>DRAG TO STEER &bull; RELEASE TO STOP</div>"
"<div class='dg'>"
"<button class='btn dir' id='bDL'  onpointerdown=\"mv('drift_left')\">DL</button>"
"<button class='btn dir' id='bFWD' onpointerdown=\"mv('forward')\">&#9650; FWD</button>"
"<button class='btn dir' id='bDR'  onpointerdown=\"mv('drift_right')\">DR</button>"
"<button class='btn dir' id='bL'   onpointerdown=\"mv('left')\">&#9668; L</button>"
"<button class='btn stop-b' id='bSTP' onpointerdown=\"mv('stop')\">&#9632;</button>"
"<button class='btn dir' id='bR'   onpointerdown=\"mv('right')\">R &#9658;</button>"
"<div></div>"
"<button class='btn dir' id='bBWD' onpointerdown=\"mv('backward')\">&#9660; BWD</button>"
"<div></div>"
"</div>"
"<div style='margin-top:12px;padding-top:10px;border-top:1px solid var(--bdr);'>"
"<div style='font-size:9px;color:var(--dim2);font-family:Share Tech Mono;letter-spacing:2px;margin-bottom:4px;'>DRIVE SPEED</div>"
"<div class='spd-row'>"
"<input class='spd-slider' type='range' id='spdSlider' min='80' max='255' value='200' oninput='updateSpeed(this.value)'>"
"<div class='spd-lbl' id='spdLbl'>200</div>"
"</div>"
"</div>"
"<div class='prow'>"
"<div class='pbtn pb-pump' id='bPump' onclick='togglePump()'>&#128166; PUMP<br><span id='pumpLbl'>OFF</span></div>"
"<div class='pbtn pb-blow' id='bBlow' onclick='toggleBlow()'>&#127756; BLOWER<br><span id='blowLbl'>OFF</span></div>"
"</div>"
"</div>"

/* SERVO PANEL */
"<div class='card'>"
"<h3><span class='ic'>&#128295;</span> Wiper / Servo Control</h3>"
"<div class='servo-arc-wrap'>"
"<div class='servo-arc'>"
"<svg id='servoSvg' width='120' height='70' viewBox='0 0 120 70'>"
"<path d='M10,65 A50,50,0,0,1,110,65' fill='none' stroke='rgba(168,85,247,0.2)' stroke-width='4' stroke-linecap='round'/>"
"<path id='servoArcFill' d='M10,65 A50,50,0,0,1,110,65' fill='none' stroke='var(--servo)' stroke-width='4' stroke-linecap='round' stroke-dasharray='157' stroke-dashoffset='157' style='transition:stroke-dashoffset 0.3s'/>"
"<line id='servoNeedle' x1='60' y1='65' x2='60' y2='18' stroke='var(--servo)' stroke-width='2.5' stroke-linecap='round' style='transform-origin:60px 65px;transform:rotate(0deg);transition:transform 0.3s'/>"
"<circle cx='60' cy='65' r='5' fill='var(--servo)' opacity='0.8'/>"
"<text x='8' y='68' fill='rgba(168,85,247,0.5)' font-size='8' font-family='Share Tech Mono'>0</text>"
"<text x='100' y='68' fill='rgba(168,85,247,0.5)' font-size='8' font-family='Share Tech Mono'>180</text>"
"</svg>"
"</div>"
"<div class='servo-angle-lbl' id='servoAngleLbl'>90</div>"
"<div class='servo-pos-lbl' id='servoPosLbl'>PARK</div>"
"</div>"
"<input class='angle-slider' type='range' id='servoSlider' min='0' max='180' value='90' oninput='servoAngle(this.value)'>"
"<div class='servo-btns'>"
"<button class='btn servo-b' onclick=\"servoPos('park')\">PARK (90)</button>"
"<button class='btn servo-b' onclick=\"servoPos('deploy')\">DEPLOY (10)</button>"
"<button class='btn servo-b' onclick=\"servoPos('boundary')\">LIFT (170)</button>"
"</div>"
"<div style='background:rgba(168,85,247,0.06);border:1px solid rgba(168,85,247,0.15);border-radius:5px;"
"padding:8px;font-family:Share Tech Mono;font-size:8px;color:var(--dim2);line-height:1.9;margin-top:8px;'>"
"<div style='color:var(--servo);font-size:9px;margin-bottom:3px;'>AUTO SERVO BEHAVIOUR</div>"
"DEPLOY: wiper sweeps during forward clean<br>"
"LIFT: wiper raised before panel boundary<br>"
"PARK: stowed during turns and travel"
"</div>"
"<div style='margin-top:10px;padding-top:10px;border-top:1px solid var(--bdr);'>"
"<button class='btn full warn-b' id='bRAM' onclick='toggleRam()'>RAMMING: OFF</button>"
"<div class='sr' style='margin-top:6px;'><span class='sk'>Tail Light</span>"
"<div style='display:flex;gap:4px;'>"
"<button class='btn warn-b' onclick='setTail(1)' style='padding:4px 8px;font-size:9px;'>ON</button>"
"<button class='btn' onclick='setTail(0)' style='padding:4px 8px;font-size:9px;'>OFF</button>"
"</div></div>"
"</div>"
"</div>"

/* IR SENSORS */
"<div class='card'>"
"<h3><span class='ic'>&#128064;</span> IR Obstacle Sensors</h3>"
"<div class='ir-g'>"
"<div class='ir-c' id='irFL'><div class='lbl'>FRONT LEFT</div><div class='dot'></div><div class='st' id='irFLst'>---</div></div>"
"<div class='ir-c' id='irFR'><div class='lbl'>FRONT RIGHT</div><div class='dot'></div><div class='st' id='irFRst'>---</div></div>"
"<div class='ir-c' id='irBL'><div class='lbl'>BACK LEFT</div><div class='dot'></div><div class='st' id='irBLst'>---</div></div>"
"<div class='ir-c' id='irBR'><div class='lbl'>BACK RIGHT</div><div class='dot'></div><div class='st' id='irBRst'>---</div></div>"
"</div>"
"<div class='zone-row'>"
"<div class='zone'><div class='zl'>FRONT ZONE</div><div class='zv' id='izF' style='color:var(--ok)'>CLEAR</div></div>"
"<div class='zone'><div class='zl'>BACK ZONE</div><div class='zv' id='izB' style='color:var(--ok)'>CLEAR</div></div>"
"</div>"
"<div class='lcd'>"
"<div class='ll' id='l1'>Dir: STOP       </div>"
"<div class='ld'></div>"
"<div class='ll' id='l2'>F:CLR  B:CLR    </div>"
"</div>"
"</div>"

/* MPU / IMU */
"<div class='card'>"
"<h3><span class='ic'>&#129517;</span> MPU-6050 IMU</h3>"
"<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:10px;'>"
"<div id='mpuBadge' class='mpu-badge fail'>NOT DETECTED</div>"
"<button class='btn info-b' onclick='resetHdg()' style='padding:4px 10px;font-size:9px;'>ZERO HDG</button>"
"</div>"
"<div class='imu-row'>"
"<div style='text-align:center;'>"
"<div class='compass'>"
"<div class='c-ring'></div>"
"<div class='c-n'>N</div><div class='c-s'>S</div><div class='c-e'>E</div><div class='c-w'>W</div>"
"<div class='c-needle' id='cNdl'></div>"
"<div class='c-dot'></div>"
"</div>"
"<div class='c-hdg' id='cHdg'>0.00</div>"
"</div>"
"<div style='text-align:center;'>"
"<div class='tilt'>"
"<div class='t-ch'></div><div class='t-cv'></div><div class='t-ring'></div>"
"<div class='t-bub' id='tBub'></div>"
"</div>"
"<div style='font-family:Share Tech Mono;font-size:9px;color:var(--dim2);margin-top:4px;'>TILT</div>"
"</div>"
"<div class='mpu-stats'>"
"<div style='font-size:8px;color:var(--dim2);font-family:Share Tech Mono;letter-spacing:2px;margin-bottom:4px;'>ACCEL (g)</div>"
"<div class='ab-row'><span class='ab-ax' style='color:#ff4500'>X</span><div class='ab-tr'><div class='ab-cn'></div><div class='ab-fl x' id='abX' style='left:50%;width:0'></div></div><span class='ab-val' id='avX'>0.000</span></div>"
"<div class='ab-row'><span class='ab-ax' style='color:#39ff14'>Y</span><div class='ab-tr'><div class='ab-cn'></div><div class='ab-fl y' id='abY' style='left:50%;width:0'></div></div><span class='ab-val' id='avY'>0.000</span></div>"
"<div class='ab-row'><span class='ab-ax' style='color:#00e5ff'>Z</span><div class='ab-tr'><div class='ab-cn'></div><div class='ab-fl z' id='abZ' style='left:50%;width:0'></div></div><span class='ab-val' id='avZ'>1.000</span></div>"
"<div class='hdg-dev'>"
"<div style='display:flex;justify-content:space-between;font-size:8px;color:var(--dim2);font-family:Share Tech Mono;margin-bottom:2px;'>"
"<span>HEADING DEV</span><span id='hdgDevVal'>0.0</span></div>"
"<div class='hdg-track'><div class='hdg-center'></div><div class='hdg-bar' id='hdgBar' style='left:50%;width:0;'></div></div>"
"<div class='hdg-labels'><span>-30</span><span>0</span><span>+30</span></div>"
"</div>"
"<div class='vib-wrap'>"
"<div style='display:flex;justify-content:space-between;font-size:8px;font-family:Share Tech Mono;color:var(--dim2);margin-bottom:2px;'>"
"<span>VIBRATION</span><span id='vibVal'>0.000g</span></div>"
"<div class='vib-track'><div class='vib-fill' id='vibFill' style='width:0'></div></div>"
"</div>"
"<div class='sr' style='margin-top:6px;'><span class='sk'>Temp</span><span class='sv' id='mpuTemp'>---</span></div>"
"<div class='sr'><span class='sk'>Gyro Z</span><span class='sv' id='sGz'>---</span></div>"
"</div>"
"</div>"
"</div>"

/* PATH RECORD */
"<div class='card'>"
"<h3><span class='ic'>&#127936;</span> Path Record &amp; Replay</h3>"
"<div style='font-size:10px;color:var(--dim2);font-family:Share Tech Mono;line-height:2;margin-bottom:10px;'>"
"1) <span style='color:var(--rec)'>START REC</span> — drive one full panel pass<br>"
"2) <span style='color:var(--warn)'>STOP REC</span> when done<br>"
"3) Place at start — <span style='color:var(--ok)'>PLAY</span> to repeat automatically"
"</div>"
"<div class='path-box'>"
"<div class='path-status'>"
"<div style='display:flex;justify-content:space-between;'>"
"<span id='pathStateLbl' style='color:var(--dim2);font-size:9px;letter-spacing:2px;'>IDLE</span>"
"<span id='pathStepsLbl' style='color:var(--info);'>0 steps</span>"
"</div>"
"<div style='margin-top:5px;height:4px;background:rgba(255,255,255,0.05);border-radius:2px;overflow:hidden;'>"
"<div id='pathProg' style='height:100%;width:0;background:var(--rec);border-radius:2px;transition:width .3s;'></div>"
"</div>"
"</div>"
"<div style='display:flex;gap:5px;margin-top:8px;'>"
"<button class='btn rec-b' id='btnRS' onclick='pathRecStart()' style='flex:1;padding:9px;'>&#9679; START REC</button>"
"<button class='btn warn-b' id='btnRST' onclick='pathRecStop()' style='flex:1;padding:9px;'>&#9632; STOP REC</button>"
"</div>"
"<div style='display:flex;gap:5px;margin-top:5px;'>"
"<button class='btn ok-b' id='btnPP' onclick='pathPlay()' style='flex:1;padding:9px;'>&#9654; PLAY</button>"
"<button class='btn stop-b' onclick='stopAuto()' style='flex:1;padding:9px;'>&#9632; STOP</button>"
"<button class='btn' id='btnPC' onclick='pathClear()' style='padding:9px;font-size:9px;color:var(--dim2);border-color:var(--bdr);'>CLR</button>"
"</div>"
"</div>"
"</div>"

/* STATUS */
"<div class='card'>"
"<h3><span class='ic'>&#128202;</span> System Status</h3>"
"<div class='sr'><span class='sk'>Direction</span><span class='sv' id='sDir'>---</span></div>"
"<div class='sr'><span class='sk'>Heading</span><span class='sv' id='sHdg'>---</span></div>"
"<div class='sr'><span class='sk'>Servo</span><span class='sv servo' id='sServo'>---</span></div>"
"<div class='sr'><span class='sk'>Speed L/R</span><span class='sv' id='sSpd'>---</span></div>"
"<div class='sr'><span class='sk'>Vibration</span><span class='sv' id='sVib'>---</span></div>"
"<div class='sr'><span class='sk'>Front Blocked</span><span class='sv' id='sFObs'>---</span></div>"
"<div class='sr'><span class='sk'>Back Blocked</span><span class='sv' id='sBObs'>---</span></div>"
"<div class='sr'><span class='sk'>Pump</span><span class='sv' id='sPumpSt'>---</span></div>"
"<div class='sr'><span class='sk'>Blower</span><span class='sv' id='sBlowSt'>---</span></div>"
"<div class='sr'><span class='sk'>Auto State</span><span class='sv' id='sAutoSt'>---</span></div>"
"<div class='sr'><span class='sk'>Panel / Strip</span><span class='sv' id='sPanelSt'>---</span></div>"
"<div class='sr'><span class='sk'>Path</span><span class='sv' id='sPathSt'>---</span></div>"
"<div class='sr'><span class='sk'>Ping</span><span class='sv' id='sPing'>---</span></div>"
"</div>"

/* SENSOR DIAG */
"<div class='card'>"
"<h3><span class='ic'>&#128295;</span> Sensor Diagnostics</h3>"
"<div style='font-size:10px;color:var(--dim2);font-family:Share Tech Mono;line-height:1.8;'>"
"IR: clear area expected CLEAR &nbsp;|&nbsp; MPU flat: Az~1.0g<br>"
"Rover: <span id='roverDims' style='color:var(--info)'>---</span>"
"</div>"
"<button class='btn full info-b' onclick='runDiag()' style='margin-top:10px;'>RUN SENSOR CHECK</button>"
"<div id='chkResult' style='margin-top:8px;'></div>"
"</div>"

/* GRID + AUTO */
"<div class='card fc'>"
"<h3><span class='ic'>&#9728;</span> Solar Panel Grid &amp; Auto Clean</h3>"
"<div class='ge-2'>"
"<div>"
"<div style='font-size:9px;color:var(--dim2);letter-spacing:2px;font-family:Share Tech Mono;margin-bottom:8px;'>PANEL LAYOUT</div>"
"<div class='ge-row'><span class='ge-lbl'>COLUMNS</span><input class='ge-inp' type='number' id='gCols' value='2' min='1' max='20' oninput='calcGrid()'></div>"
"<div class='ge-row'><span class='ge-lbl'>ROWS</span><input class='ge-inp' type='number' id='gRows' value='1' min='1' max='20' oninput='calcGrid()'></div>"
"<div class='ge-row'><span class='ge-lbl'>PANEL WIDTH (cm)</span><input class='ge-inp' type='number' id='gPW' value='200' min='20' max='800' oninput='calcGrid()'></div>"
"<div class='ge-row'><span class='ge-lbl'>PANEL HEIGHT (cm)</span><input class='ge-inp' type='number' id='gPH' value='170' min='20' max='800' oninput='calcGrid()'></div>"
"<div class='ge-row'><span class='ge-lbl'>COL GAP (cm)</span><input class='ge-inp' type='number' id='gGap' value='5' min='0' max='300' oninput='calcGrid()'></div>"
"<div class='ge-row'><span class='ge-lbl'>ROW GAP (cm)</span><input class='ge-inp' type='number' id='gRowGap' value='10' min='0' max='300' oninput='calcGrid()'></div>"
"<div class='ge-row'><span class='ge-lbl'>PASSES PER STRIP</span><input class='ge-inp' type='number' id='gPasses' value='1' min='1' max='3' oninput='calcGrid()'></div>"
"<div style='margin-top:8px;display:flex;flex-wrap:wrap;gap:8px;'>"
"<label class='chk-row'><input type='checkbox' id='gWash' checked> Pump during clean</label>"
"<label class='chk-row'><input type='checkbox' id='gBlow'> Blower during clean</label>"
"</div>"
"<div id='calcInfo'></div>"
"<div style='display:flex;gap:6px;margin-top:10px;'>"
"<button class='btn ok-b' onclick='saveGrid()' style='flex:1;padding:9px;'>SAVE GRID</button>"
"</div>"
"<div id='gridMsg' style='font-family:Share Tech Mono;font-size:9px;color:var(--acc);margin-top:6px;min-height:14px;'></div>"
"<div class='auto-box'>"
"<div class='auto-state idle' id='autoStateLabel'>IDLE — READY TO CLEAN</div>"
"<div class='prog-track'><div class='prog-fill' id='progFill' style='width:0'></div></div>"
"<div class='prog-labels'>"
"<span id='stripsDone'>0 strips done</span>"
"<span id='progPct'>0%</span>"
"<span id='stripsTotal'>/ 0 total</span>"
"</div>"
"<div class='panel-tracker' id='panelTracker'></div>"
"</div>"
"<button class='btn full ok-b xl' id='startBtn' onclick='startAuto()' style='margin-top:10px;'>START AUTO CLEAN</button>"
"<button class='btn full warn-b' id='pauseBtn' onclick='pauseAuto()' style='display:none;margin-top:4px;'>PAUSE</button>"
"<button class='btn full info-b' id='resumeBtn' onclick='resumeAuto()' style='display:none;margin-top:4px;'>RESUME</button>"
"<button class='btn full stop-b' id='stopBtn' onclick='stopAuto()' style='display:none;margin-top:4px;'>STOP AUTO CLEAN</button>"
"</div>"
"<div>"
"<div style='font-size:9px;color:var(--dim2);letter-spacing:2px;font-family:Share Tech Mono;margin-bottom:8px;'>PATTERN PREVIEW</div>"
"<div style='background:var(--s2);border:1px solid var(--bdr);border-radius:6px;padding:8px;display:flex;justify-content:center;'>"
"<canvas id='gpCanvas' width='280' height='220'></canvas>"
"</div>"
"<div id='gpInfo'></div>"
"<div style='margin-top:8px;padding:8px;background:var(--s2);border-radius:5px;"
"font-family:Share Tech Mono;font-size:8px;color:var(--dim2);line-height:1.9;'>"
"<div style='color:var(--acc);font-size:9px;margin-bottom:4px;'>LEGEND</div>"
"Amber arrows: FWD sweep (gyro-guided PID)<br>"
"Grey: lateral step turns<br>"
"Cyan: inter-panel advance<br>"
"Yellow dot: start position<br>"
"Purple: servo deploy / lift points"
"</div>"
"</div>"
"</div>"
"</div>"

"</div>"

/* ═════════════ JAVASCRIPT ═════════════ */
"<script>"

/* ── Modal helper (replaces confirm()) ── */
"var _modalCb=null;"
"function showModal(msg,cb){"
"  document.getElementById('modalMsg').textContent=msg;"
"  _modalCb=cb;"
"  document.getElementById('modalOverlay').classList.add('show');"
"}"
"document.addEventListener('DOMContentLoaded',function(){"
"  document.getElementById('modalOk').addEventListener('click',function(){"
"    document.getElementById('modalOverlay').classList.remove('show');"
"    if(_modalCb){var c=_modalCb;_modalCb=null;c(true);}"
"  });"
"  document.getElementById('modalCancel').addEventListener('click',function(){"
"    document.getElementById('modalOverlay').classList.remove('show');"
"    _modalCb=null;"
"  });"
"});"

/* ── Toast ── */
"function toast(msg,type){"
"  var c=document.getElementById('toastWrap');"
"  var t=document.createElement('div');"
"  t.className='toast '+(type||'ok');"
"  t.textContent=msg;"
"  c.appendChild(t);"
"  setTimeout(function(){if(t.parentNode)t.parentNode.removeChild(t);},4100);"
"}"

/* ── State ── */
"var lastFB=0,lastBB=0,ramOn=0,pumpOn=0,blowOn=0;"
"var lastCmd='',inFlight=0,pendingCmd=null;"
"var autoRunning=false,autoPaused=false,lastAutoRunning=false,lastAutoPaused=false;"
"var pathRecording=false,lastPathRecording=false;"
"var pathPlayback=false,lastPathPlayback=false;"
"var pathSteps=0;"

/* ── Move ── */
"function mv(dir){"
"  if(autoRunning||pathPlayback)return;"
"  if(dir===lastCmd&&dir!=='stop')return;"
"  if(inFlight>0){pendingCmd=dir;return;}"
"  sendMove(dir);"
"}"
"function sendMove(dir){"
"  lastCmd=dir;inFlight++;hiBtn(dir);"
"  fetch('/move?dir='+dir)"
"    .then(function(r){return r.text();})"
"    .then(function(t){"
"      inFlight--;flushPend();"
"      if(t.indexOf('BLOCKED')===0)toast(t,'warn');"
"    })"
"    .catch(function(){inFlight--;flushPend();});"
"}"
"function flushPend(){"
"  if(pendingCmd!==null){var c=pendingCmd;pendingCmd=null;sendMove(c);}"
"}"
"function hiBtn(dir){"
"  var map={forward:'bFWD',backward:'bBWD',left:'bL',right:'bR',"
"           drift_left:'bDL',drift_right:'bDR',stop:'bSTP'};"
"  ['bFWD','bBWD','bL','bR','bDL','bDR','bSTP'].forEach(function(id){"
"    var el=document.getElementById(id);"
"    if(el)el.classList.remove('active');"
"  });"
"  var id=map[dir];"
"  if(id){var el=document.getElementById(id);if(el)el.classList.add('active');}"
"}"

/* ── Tail / Ram ── */
"function setTail(s){"
"  fetch('/tail?state='+(s?'on':'off'))"
"    .then(function(r){return r.text();})"
"    .then(function(t){toast(t,'ok');});"
"}"
"function toggleRam(){"
"  ramOn=!ramOn;"
"  fetch('/ramming?state='+(ramOn?'on':'off'));"
"  var b=document.getElementById('bRAM');"
"  if(ramOn){"
"    b.textContent='RAMMING: ON';"
"    b.style.background='rgba(255,69,0,0.25)';"
"    b.style.boxShadow='0 0 16px rgba(255,69,0,0.5)';"
"  }else{"
"    b.textContent='RAMMING: OFF';"
"    b.style.background='';"
"    b.style.boxShadow='';"
"  }"
"}"

/* ── Pump / Blower ── */
"function togglePump(){"
"  pumpOn=!pumpOn;"
"  fetch('/pump?state='+(pumpOn?'on':'off'));"
"  updatePumpUI();"
"}"
"function toggleBlow(){"
"  blowOn=!blowOn;"
"  fetch('/blower?state='+(blowOn?'on':'off'));"
"  updateBlowUI();"
"}"
"function updatePumpUI(){"
"  var b=document.getElementById('bPump'),l=document.getElementById('pumpLbl');"
"  if(pumpOn){b.classList.add('on');l.textContent='ON';}"
"  else{b.classList.remove('on');l.textContent='OFF';}"
"}"
"function updateBlowUI(){"
"  var b=document.getElementById('bBlow'),l=document.getElementById('blowLbl');"
"  if(blowOn){b.classList.add('on');l.textContent='ON';}"
"  else{b.classList.remove('on');l.textContent='OFF';}"
"}"

/* ── Speed ── */
"function updateSpeed(v){"
"  document.getElementById('spdLbl').textContent=v;"
"  fetch('/motor_speed?spd='+v);"
"}"

/* ── Heading reset ── */
"function resetHdg(){"
"  fetch('/mpu_reset').then(function(){toast('Heading zeroed','ok');});"
"}"

/* ── Servo ── */
"function servoPos(p){"
"  fetch('/servo?pos='+p)"
"    .then(function(r){return r.text();})"
"    .then(function(){toast('Servo: '+p.toUpperCase(),'info');});"
"}"
"function servoAngle(v){"
"  fetch('/servo?angle='+v);"
"  updateServoUI(parseInt(v));"
"}"
"function updateServoUI(angle){"
"  if(isNaN(angle))return;"
"  document.getElementById('servoAngleLbl').textContent=angle;"
"  var ndl=document.getElementById('servoNeedle');"
"  if(ndl){var rot=angle-90;ndl.style.transform='rotate('+rot+'deg)';}"
"  var sl=document.getElementById('servoSlider');"
"  if(sl&&parseInt(sl.value)!==angle)sl.value=angle;"
"  var af=document.getElementById('servoArcFill');"
"  if(af){var offset=Math.round(157-angle/180*157);af.setAttribute('stroke-dashoffset',offset);}"
"  var pl=document.getElementById('servoPosLbl');"
"  if(pl){"
"    if(angle<=15)pl.textContent='DEPLOYED';"
"    else if(angle>=160)pl.textContent='LIFTED';"
"    else if(angle>70&&angle<110)pl.textContent='PARK';"
"    else pl.textContent='CUSTOM';"
"  }"
"}"

/* ── Auto clean ── */
"function startAuto(){"
"  showModal('Start auto clean?\\n\\nPlace rover at TOP-LEFT corner, facing DOWN the panel.',function(ok){"
"    if(!ok)return;"
"    fetch('/auto')"
"      .then(function(r){return r.text();})"
"      .then(function(t){"
"        if(t==='ALREADY_RUNNING'){toast('Already running','warn');return;}"
"        if(t.indexOf('ERROR')===0){toast(t,'err');return;}"
"      })"
"      .catch(function(){toast('Start failed','err');});"
"  });"
"}"
"function stopAuto(){"
"  fetch('/stop_auto').then(function(){toast('Stop requested','warn');});"
"}"
"function pauseAuto(){"
"  fetch('/pause_auto').then(function(){toast('Paused','info');});"
"}"
"function resumeAuto(){"
"  fetch('/resume_auto').then(function(){toast('Resumed','ok');});"
"}"

/* ── Path recording ── */
"function pathRecStart(){"
"  fetch('/path_record_start')"
"    .then(function(r){return r.text();})"
"    .then(function(t){"
"      if(t==='RECORDING_STARTED'){toast('Recording started!','rec');}"
"      else toast(t,'warn');"
"    })"
"    .catch(function(){toast('Failed','err');});"
"}"
"function pathRecStop(){"
"  fetch('/path_record_stop')"
"    .then(function(r){return r.text();})"
"    .then(function(t){toast(t,'ok');})"
"    .catch(function(){toast('Failed','err');});"
"}"
"function pathPlay(){"
"  if(pathSteps===0){toast('No path recorded','warn');return;}"
"  showModal('Play recorded path?\\n\\nPlace rover at START POSITION first!',function(ok){"
"    if(!ok)return;"
"    fetch('/path_play')"
"      .then(function(r){return r.text();})"
"      .then(function(t){"
"        if(t==='PLAYBACK_STARTED'){toast('Playback started','ok');}"
"        else toast(t,'warn');"
"      })"
"      .catch(function(){toast('Failed','err');});"
"  });"
"}"
"function pathClear(){"
"  if(pathSteps===0){"
"    fetch('/path_clear').then(function(r){return r.text();}).then(function(t){toast(t,'ok');});"
"    return;"
"  }"
"  showModal('Clear '+pathSteps+' recorded steps?',function(ok){"
"    if(!ok)return;"
"    fetch('/path_clear').then(function(r){return r.text();}).then(function(t){toast(t,'ok');});"
"  });"
"}"

/* ── IR helper ── */
"function setIR(cid,sid,blocked){"
"  var c=document.getElementById(cid),s=document.getElementById(sid);"
"  if(!c||!s)return;"
"  c.className='ir-c '+(blocked?'blocked':'clear');"
"  s.textContent=blocked?'BLOCKED':'CLEAR';"
"}"

/* ── Accel bar ── */
"function setAccel(fid,vid,v){"
"  var f=document.getElementById(fid),ve=document.getElementById(vid);"
"  if(!f||!ve)return;"
"  var p=Math.min(48,Math.abs(v)/2*48);"
"  if(v>=0){f.style.left='50%';f.style.width=p+'%';}"
"  else{f.style.left=(50-p)+'%';f.style.width=p+'%';}"
"  ve.textContent=(v>=0?'+':'')+v.toFixed(3)+' g';"
"}"

/* ── Status poll ── */
"function pollStatus(){"
"  var t0=Date.now();"
"  fetch('/status')"
"    .then(function(r){return r.json();})"
"    .then(function(d){"
"      var ping=Date.now()-t0;"
"      document.getElementById('sPing').textContent=ping+' ms';"
"      var cd=document.getElementById('connDot');"
"      cd.className=ping<400?'ok':'err';"

"      document.getElementById('sDir').textContent=d.direction||'---';"

"      var hdg=d.heading||0;"
"      document.getElementById('sHdg').textContent=hdg.toFixed(2)+'deg';"
"      var gz=d.gyro_z||0;"
"      document.getElementById('sGz').textContent=gz.toFixed(3)+' deg/s';"
"      document.getElementById('sSpd').textContent=(d.speed_left||200)+' / '+(d.speed_right||200);"
"      document.getElementById('sServo').textContent=(d.servo_angle||90)+'deg '+(d.servo_pos||'PARK');"

"      var ndl=document.getElementById('cNdl'),h=document.getElementById('cHdg');"
"      if(ndl)ndl.style.transform='rotate('+hdg+'deg)';"
"      if(h)h.textContent=hdg.toFixed(2);"

"      var bub=document.getElementById('tBub');"
"      if(bub){"
"        var sc=22;"
"        var dx=Math.max(-sc,Math.min(sc,(d.accel_x||0)*sc));"
"        var dy=Math.max(-sc,Math.min(sc,-(d.accel_y||0)*sc));"
"        bub.style.left='calc(50% + '+dx+'px)';"
"        bub.style.top='calc(50% + '+dy+'px)';"
"      }"

"      setAccel('abX','avX',d.accel_x||0);"
"      setAccel('abY','avY',d.accel_y||0);"
"      setAccel('abZ','avZ',d.accel_z||0);"

"      var hdgErr=gz*0.5;"
"      var hdgBar=document.getElementById('hdgBar');"
"      var hdgDev=document.getElementById('hdgDevVal');"
"      if(hdgBar&&hdgDev){"
"        var maxErr=30;"
"        var pct=Math.min(50,Math.abs(hdgErr)/maxErr*50);"
"        if(hdgErr>=0){"
"          hdgBar.style.left='50%';"
"          hdgBar.style.width=pct+'%';"
"          hdgBar.style.background='var(--err)';"
"        }else{"
"          hdgBar.style.left=(50-pct)+'%';"
"          hdgBar.style.width=pct+'%';"
"          hdgBar.style.background='var(--acc3)';"
"        }"
"        hdgDev.textContent=hdgErr.toFixed(1);"
"      }"

"      var vib=d.vib||0;"
"      var vf=document.getElementById('vibFill'),vv=document.getElementById('vibVal');"
"      if(vf){"
"        vf.style.width=Math.min(100,vib/2*100)+'%';"
"        vf.style.background=vib<0.1?'var(--ok)':vib<0.4?'var(--warn)':'var(--err)';"
"      }"
"      if(vv)vv.textContent=vib.toFixed(3)+' g';"
"      document.getElementById('sVib').textContent=vib.toFixed(3)+' g';"

"      var mb=document.getElementById('mpuBadge');"
"      if(mb){"
"        mb.textContent=d.mpu_ready?'CONNECTED':'NOT DETECTED';"
"        mb.className='mpu-badge '+(d.mpu_ready?'ok':'fail');"
"      }"
"      document.getElementById('mpuTemp').textContent=(d.mpu_temp||'--')+'C';"

"      setIR('irFL','irFLst',d.ir_fl);"
"      setIR('irFR','irFRst',d.ir_fr);"
"      setIR('irBL','irBLst',d.ir_bl);"
"      setIR('irBR','irBRst',d.ir_br);"
"      var izF=document.getElementById('izF'),izB=document.getElementById('izB');"
"      if(izF){izF.textContent=d.front_blocked?'BLOCKED':'CLEAR';izF.style.color=d.front_blocked?'var(--err)':'var(--ok)';}"
"      if(izB){izB.textContent=d.back_blocked?'BLOCKED':'CLEAR';izB.style.color=d.back_blocked?'var(--err)':'var(--ok)';}"

"      var obs=!d.ramming&&(d.front_blocked||d.back_blocked);"
"      document.getElementById('obsBanner').style.display=obs?'block':'none';"
"      if(!d.ramming){"
"        if(!lastFB&&d.front_blocked)toast('FRONT OBSTACLE','warn');"
"        if(!lastBB&&d.back_blocked)toast('BACK OBSTACLE','warn');"
"      }"
"      lastFB=d.front_blocked?1:0;lastBB=d.back_blocked?1:0;"

"      if(d.pump!=(pumpOn?1:0)){pumpOn=d.pump?1:0;updatePumpUI();}"
"      if(d.blower!=(blowOn?1:0)){blowOn=d.blower?1:0;updateBlowUI();}"
"      document.getElementById('sPumpSt').textContent=d.pump?'ON':'OFF';"
"      document.getElementById('sPumpSt').className='sv '+(d.pump?'pump':'ok');"
"      document.getElementById('sBlowSt').textContent=d.blower?'ON':'OFF';"
"      document.getElementById('sBlowSt').className='sv '+(d.blower?'blow':'ok');"

"      updateServoUI(d.servo_angle||90);"
"      document.getElementById('sServo').textContent=(d.servo_angle||90)+'deg '+(d.servo_pos||'PARK');"

"      updateAutoUI(d);"
"      updatePathUI(d);"

"      document.getElementById('sFObs').textContent=d.front_blocked?'BLOCKED':'CLEAR';"
"      document.getElementById('sFObs').className='sv '+(d.front_blocked?'warn':'ok');"
"      document.getElementById('sBObs').textContent=d.back_blocked?'BLOCKED':'CLEAR';"
"      document.getElementById('sBObs').className='sv '+(d.back_blocked?'warn':'ok');"
"      document.getElementById('sPanelSt').textContent='Panel '+(d.auto_panel||0)+' Strip '+(d.auto_strip||0);"

"      var l1='Dir: '+((d.direction||'STOP').substring(0,7));"
"      var l2;"
"      if(d.path_recording)l2='REC:'+d.path_steps+' STEPS';"
"      else if(d.path_playback)l2='PLAYING:'+d.path_steps+' STEPS';"
"      else if(d.auto_running)l2='AUTO:'+d.auto_pct+'% P'+(d.auto_panel||0)+'/S'+(d.auto_strip||0);"
"      else l2='F:'+(d.front_blocked?'BLK':'CLR')+' B:'+(d.back_blocked?'BLK':'CLR')+' H:'+Math.round(hdg);"
"      document.getElementById('l1').textContent=l1.padEnd(16).substring(0,16);"
"      document.getElementById('l2').textContent=(l2||'').padEnd(16).substring(0,16);"
"    })"
"    .catch(function(){"
"      document.getElementById('connDot').className='err';"
"    });"
"}"
"setInterval(pollStatus,400);"

/* ── Auto UI update ── */
"function updateAutoUI(d){"
"  var running=!!(d.auto_running||d.path_playback);"
"  var paused=!!d.auto_paused;"
"  var pct=d.auto_pct||0;"
"  var done=d.auto_strips_done||0;"
"  var total=d.auto_strips_total||0;"
"  var state=d.auto_state||'IDLE';"

"  document.getElementById('progFill').style.width=pct+'%';"
"  document.getElementById('progPct').textContent=pct+'%';"
"  document.getElementById('stripsDone').textContent=done+' strips done';"
"  document.getElementById('stripsTotal').textContent='/ '+total+' total';"

"  var sl=document.getElementById('autoStateLabel');"
"  var sb=document.getElementById('startBtn');"
"  var pb=document.getElementById('pauseBtn');"
"  var rb=document.getElementById('resumeBtn');"
"  var xb=document.getElementById('stopBtn');"
"  var lk=document.getElementById('autoLock');"
"  var sas=document.getElementById('sAutoSt');"
"  var pb2=document.getElementById('pauseBanner');"

"  if(running&&!paused){"
"    sl.className='auto-state running';"
"    sl.textContent=d.path_playback?'PATH REPLAY IN PROGRESS...':'AUTO CLEAN IN PROGRESS...';"
"    if(sas){sas.textContent='RUNNING';sas.className='sv ok';}"
"    if(sb)sb.style.display='none';"
"    if(pb)pb.style.display='block';"
"    if(rb)rb.style.display='none';"
"    if(xb)xb.style.display='block';"
"    if(lk)lk.style.display='block';"
"    if(pb2)pb2.style.display='none';"
"  }else if(paused){"
"    sl.className='auto-state paused';"
"    sl.textContent='PAUSED — PRESS RESUME';"
"    if(sas){sas.textContent='PAUSED';sas.className='sv info';}"
"    if(sb)sb.style.display='none';"
"    if(pb)pb.style.display='none';"
"    if(rb)rb.style.display='block';"
"    if(xb)xb.style.display='block';"
"    if(lk)lk.style.display='block';"
"    if(pb2)pb2.style.display='block';"
"  }else if(state==='DONE'){"
"    sl.className='auto-state done';"
"    sl.textContent='CLEAN COMPLETE';"
"    if(sas){sas.textContent='DONE';sas.className='sv ok';}"
"    if(sb)sb.style.display='block';"
"    if(pb)pb.style.display='none';"
"    if(rb)rb.style.display='none';"
"    if(xb)xb.style.display='none';"
"    if(lk)lk.style.display='none';"
"    if(pb2)pb2.style.display='none';"
"  }else{"
"    sl.className='auto-state idle';"
"    sl.textContent='IDLE — READY TO CLEAN';"
"    if(sas){sas.textContent='IDLE';sas.className='sv ok';}"
"    if(sb)sb.style.display='block';"
"    if(pb)pb.style.display='none';"
"    if(rb)rb.style.display='none';"
"    if(xb)xb.style.display='none';"
"    if(lk)lk.style.display='none';"
"    if(pb2)pb2.style.display='none';"
"  }"

"  if(!lastAutoRunning&&running)toast('Auto clean started','ok');"
"  if(lastAutoRunning&&!running&&state==='DONE')toast('Auto clean COMPLETE','ok');"
"  if(lastAutoRunning&&!running&&state==='IDLE')toast('Auto clean stopped','warn');"
"  lastAutoRunning=running;autoRunning=running;"
"  lastAutoPaused=paused;autoPaused=paused;"
"}"

/* ── Path UI update ── */
"function updatePathUI(d){"
"  var rec=!!d.path_recording;"
"  var play=!!d.path_playback;"
"  var steps=d.path_steps||0;"
"  pathRecording=rec;pathPlayback=play;pathSteps=steps;"

"  var sl=document.getElementById('pathStateLbl');"
"  var ss=document.getElementById('pathStepsLbl');"
"  var ri=document.getElementById('recInd');"
"  var rb=document.getElementById('recBanner');"
"  var pp=document.getElementById('pathProg');"
"  var sps=document.getElementById('sPathSt');"

"  if(sl)sl.textContent=rec?'RECORDING':play?'PLAYING':'IDLE';"
"  if(sl)sl.style.color=rec?'var(--rec)':play?'var(--ok)':'var(--dim2)';"
"  if(ss)ss.textContent=steps+' steps';"
"  if(ri)ri.style.display=rec?'inline':'none';"
"  if(rb)rb.style.display=rec?'block':'none';"
"  if(pp)pp.style.width=(steps/256*100)+'%';"

"  if(sps){"
"    if(rec){sps.textContent='REC('+steps+')';sps.className='sv rec-on';}"
"    else if(play){sps.textContent='PLAY('+steps+')';sps.className='sv ok';}"
"    else if(steps>0){sps.textContent=steps+' stored';sps.className='sv';}"
"    else{sps.textContent='empty';sps.className='sv';}"
"  }"

"  var bpp=document.getElementById('btnPP');"
"  if(bpp)bpp.disabled=(steps===0||rec||play||autoRunning);"
"  var bpc=document.getElementById('btnPC');"
"  if(bpc)bpc.disabled=(rec||play||autoRunning);"

"  if(!lastPathRecording&&rec)toast('Recording started','rec');"
"  if(lastPathRecording&&!rec)toast('Saved: '+steps+' steps','ok');"
"  if(!lastPathPlayback&&play)toast('Playback started','ok');"
"  if(lastPathPlayback&&!play&&!autoRunning)toast('Playback complete','ok');"
"  lastPathRecording=rec;lastPathPlayback=play;"
"}"

/* ── Sensor diag ── */
"function runDiag(){"
"  var r=document.getElementById('chkResult');"
"  r.innerHTML='<div style=\"font-family:Share Tech Mono;font-size:9px;color:var(--dim2)\">Checking...</div>';"
"  fetch('/sensor_check')"
"    .then(function(r){return r.json();})"
"    .then(function(d){"
"      var rdEl=document.getElementById('roverDims');"
"      if(rdEl)rdEl.textContent=(d.rover_w_cm||'?')+'cm x '+(d.rover_d_cm||'?')+'cm';"
"      function row(name,status,note){"
"        var cls=status==='OK'?'cok':status==='FAIL'?'cfail':'cna';"
"        return '<tr><td>'+name+'</td><td class=\"'+cls+'\">'+status+'</td><td style=\"color:var(--dim2)\">'+note+'</td></tr>';"
"      }"
"      var rows='';"
"      rows+=row('Servo',d.servo_enabled?'OK':'N/A','Pin 23 Angle: '+d.servo_angle);"
"      rows+=row('IR',d.ir_enabled?'OK':'N/A',d.ir_enabled?'4 sensors':'IR_ENABLED=0');"
"      if(d.ir_enabled){"
"        rows+=row('IR FL',d.ir_fl.blocked?'BLOCKED':'CLEAR','Pin '+d.ir_fl.pin);"
"        rows+=row('IR FR',d.ir_fr.blocked?'BLOCKED':'CLEAR','Pin '+d.ir_fr.pin);"
"        rows+=row('IR BL',d.ir_bl.blocked?'BLOCKED':'CLEAR','Pin '+d.ir_bl.pin);"
"        rows+=row('IR BR',d.ir_br.blocked?'BLOCKED':'CLEAR','Pin '+d.ir_br.pin);"
"      }"
"      rows+=row('MPU',d.mpu_enabled?'OK':'N/A','MPU_ENABLED');"
"      if(d.mpu_enabled){"
"        rows+=row('WHO_AM_I',d.mpu_ready?'OK':'FAIL',d.mpu_ready?'Sensor found':'Check SDA/SCL wiring');"
"        if(d.mpu_ready){"
"          var azOk=Math.abs(d.mpu_accel_z-1.0)<0.3;"
"          rows+=row('Accel Z',azOk?'OK':'WARN',d.mpu_accel_z.toFixed(3)+'g (expect ~1.0)');"
"          rows+=row('Heading','OK',d.mpu_heading.toFixed(2));"
"          rows+=row('Temp','OK',d.mpu_temp_c+'C');"
"        }"
"      }"
"      r.innerHTML='<table class=\"chk-tbl\"><thead><tr><th>SENSOR</th><th>STATUS</th><th>DETAIL</th></tr></thead><tbody>'+rows+'</tbody></table>';"
"    })"
"    .catch(function(){"
"      r.innerHTML='<div style=\"color:var(--err);font-family:Share Tech Mono;font-size:10px\">Request failed</div>';"
"    });"
"}"

/* ── Grid calc ── */
"function calcGrid(){"
"  var cols=parseInt(document.getElementById('gCols').value)||1;"
"  var rows=parseInt(document.getElementById('gRows').value)||1;"
"  var pw=parseInt(document.getElementById('gPW').value)||200;"
"  var ph=parseInt(document.getElementById('gPH').value)||170;"
"  var gap=parseInt(document.getElementById('gGap').value)||5;"
"  var rgap=parseInt(document.getElementById('gRowGap').value)||10;"
"  var passes=parseInt(document.getElementById('gPasses').value)||1;"
"  var rw=58,rd=51;"
"  var strips=Math.ceil(ph/rw);"
"  var total=strips*cols*rows*passes;"
"  var fwdSec=pw*0.015;"
"  var stepSec=rw*0.015+1.8;"
"  var estSec=(fwdSec*passes+stepSec*(strips-1)+2)*cols*rows;"
"  var ci=document.getElementById('calcInfo');"
"  if(ci)ci.innerHTML="
"    '<span style=\"color:var(--info)\">Rover: '+rw+'cm x '+rd+'cm</span><br>'"
"    +'Strips/panel: '+strips+' @ '+rw+'cm each<br>'"
"    +'Total passes: '+total+'<br>'"
"    +'Est. time: ~'+Math.round(estSec/60)+'m '+Math.round(estSec%60)+'s';"
"  drawGrid({cols:cols,rows:rows,pw:pw,ph:ph,gap:gap,rgap:rgap,passes:passes});"
"}"

"function saveGrid(){"
"  var cols=parseInt(document.getElementById('gCols').value)||2;"
"  var rows=parseInt(document.getElementById('gRows').value)||1;"
"  var pw=parseInt(document.getElementById('gPW').value)||200;"
"  var ph=parseInt(document.getElementById('gPH').value)||170;"
"  var gap=parseInt(document.getElementById('gGap').value)||5;"
"  var rgap=parseInt(document.getElementById('gRowGap').value)||10;"
"  var passes=parseInt(document.getElementById('gPasses').value)||1;"
"  var wash=document.getElementById('gWash').checked?1:0;"
"  var blow=document.getElementById('gBlow').checked?1:0;"
"  fetch('/set_grid?cols='+cols+'&rows='+rows+'&pw='+pw+'&ph='+ph"
"    +'&gap='+gap+'&rowgap='+rgap+'&wash='+wash+'&blow='+blow+'&passes='+passes)"
"  .then(function(r){return r.json();})"
"  .then(function(d){"
"    document.getElementById('gridMsg').textContent='Saved: '+d.cols+'x'+d.rows+' panels, '+d.total_strips+' total strips';"
"    toast('Grid saved: '+d.total_strips+' strips','ok');"
"  })"
"  .catch(function(){toast('Save failed','err');});"
"}"

"function loadGrid(){"
"  fetch('/get_grid')"
"    .then(function(r){return r.json();})"
"    .then(function(d){"
"      document.getElementById('gCols').value=d.cols;"
"      document.getElementById('gRows').value=d.rows;"
"      document.getElementById('gPW').value=d.pw;"
"      document.getElementById('gPH').value=d.ph;"
"      document.getElementById('gGap').value=d.gap;"
"      document.getElementById('gRowGap').value=d.rowgap||10;"
"      document.getElementById('gPasses').value=d.passes||1;"
"      document.getElementById('gWash').checked=d.wash===1;"
"      document.getElementById('gBlow').checked=d.blow===1;"
"      if(d.rover_w_cm){"
"        var rd=document.getElementById('roverDims');"
"        if(rd)rd.textContent=d.rover_w_cm+'cm x '+d.rover_d_cm+'cm';"
"      }"
"      calcGrid();"
"    })"
"    .catch(function(){calcGrid();});"
"}"

/* ── Canvas draw ── */
"function drawGrid(d){"
"  var cv=document.getElementById('gpCanvas');"
"  if(!cv)return;"
"  var ctx=cv.getContext('2d');"
"  var W=cv.width,H=cv.height;"
"  ctx.clearRect(0,0,W,H);"

"  var pw=d.pw||200,ph=d.ph||170;"
"  var cols=d.cols||1,rows=d.rows||1;"
"  var gap=d.gap||5,rgap=d.rgap||10;"
"  var passes=d.passes||1;"
"  var rw=58;"
"  var strips=Math.ceil(ph/rw);"
"  var sh=ph/strips;"
"  var totalW=cols*pw+(cols-1)*gap;"
"  var totalH=rows*ph+(rows-1)*rgap;"
"  var sc=Math.min((W-20)/totalW,(H-20)/totalH);"
"  var ox=(W-totalW*sc)/2,oy=(H-totalH*sc)/2;"

"  for(var ri=0;ri<rows;ri++){for(var ci=0;ci<cols;ci++){"
"    var px=ox+(ci*(pw+gap))*sc;"
"    var py=oy+(ri*(ph+rgap))*sc;"
"    var pws=pw*sc,phs=ph*sc;"

"    ctx.fillStyle='rgba(30,50,20,0.6)';"
"    ctx.fillRect(px,py,pws,phs);"
"    ctx.strokeStyle='rgba(255,180,0,0.5)';"
"    ctx.lineWidth=1.5;"
"    ctx.setLineDash([]);"
"    ctx.strokeRect(px,py,pws,phs);"

"    ctx.strokeStyle='rgba(255,180,0,0.18)';"
"    ctx.lineWidth=0.5;"
"    ctx.setLineDash([3,3]);"
"    for(var s=1;s<strips;s++){"
"      var sy=py+s*sh*sc;"
"      ctx.beginPath();ctx.moveTo(px,sy);ctx.lineTo(px+pws,sy);ctx.stroke();"
"    }"
"    ctx.setLineDash([]);"

"    for(var s=0;s<strips;s++){"
"      var sy=py+(s+0.5)*sh*sc;"
"      ctx.strokeStyle='rgba(255,180,0,0.8)';"
"      ctx.lineWidth=1.5;"
"      ctx.beginPath();ctx.moveTo(px+pws*0.12,sy);ctx.lineTo(px+pws*0.82,sy);ctx.stroke();"
"      ctx.beginPath();ctx.moveTo(px+pws*0.72,sy-4);ctx.lineTo(px+pws*0.82,sy);ctx.lineTo(px+pws*0.72,sy+4);ctx.stroke();"

"      var liftX=px+pws*0.82;"
"      ctx.strokeStyle='rgba(168,85,247,0.6)';"
"      ctx.lineWidth=1;"
"      ctx.beginPath();ctx.moveTo(liftX,sy-6);ctx.lineTo(liftX,sy+6);ctx.stroke();"

"      if(passes>1){"
"        ctx.strokeStyle='rgba(255,180,0,0.3)';"
"        ctx.lineWidth=0.8;"
"        ctx.setLineDash([2,2]);"
"        for(var p=1;p<passes;p++){"
"          var psy=sy+p*3;"
"          ctx.beginPath();ctx.moveTo(px+pws*0.12,psy);ctx.lineTo(px+pws*0.82,psy);ctx.stroke();"
"        }"
"        ctx.setLineDash([]);"
"      }"

"      if(s<strips-1){"
"        ctx.strokeStyle='rgba(0,229,255,0.5)';"
"        ctx.lineWidth=0.8;"
"        var ney=py+(s+1)*sh*sc;"
"        var ex=px+pws;"
"        ctx.beginPath();ctx.moveTo(ex,sy);ctx.lineTo(ex,ney);ctx.stroke();"
"        ctx.beginPath();ctx.moveTo(ex-4,ney-6);ctx.lineTo(ex,ney);ctx.lineTo(ex-4,ney+6);ctx.stroke();"
"      }"
"    }"

"    if(ci<cols-1){"
"      ctx.strokeStyle='rgba(0,229,255,0.45)';"
"      ctx.lineWidth=1;"
"      ctx.setLineDash([3,2]);"
"      var gx0=px+pws,gx1=gx0+gap*sc,gmy=py+phs/2;"
"      ctx.beginPath();ctx.moveTo(gx0,gmy);ctx.lineTo(gx1,gmy);ctx.stroke();"
"      ctx.setLineDash([]);"
"      ctx.beginPath();ctx.moveTo(gx1-5,gmy-3);ctx.lineTo(gx1,gmy);ctx.lineTo(gx1-5,gmy+3);ctx.stroke();"
"    }"
"  }}"

"  if(rows>1){"
"    ctx.strokeStyle='rgba(0,229,255,0.35)';"
"    ctx.lineWidth=0.8;"
"    ctx.setLineDash([3,2]);"
"    for(var ri2=0;ri2<rows-1;ri2++){"
"      var ry0=oy+(ri2+1)*ph*sc+ri2*rgap*sc;"
"      var ry1=ry0+rgap*sc;"
"      var mx=ox+10;"
"      ctx.beginPath();ctx.moveTo(mx,ry0);ctx.lineTo(mx,ry1);ctx.stroke();"
"    }"
"    ctx.setLineDash([]);"
"  }"

"  ctx.fillStyle='#ffb400';"
"  ctx.beginPath();ctx.arc(ox+7,oy+7,5,0,2*Math.PI);ctx.fill();"
"  ctx.strokeStyle='#000';ctx.lineWidth=1;ctx.stroke();"

"  var strips2=Math.ceil(ph/rw);"
"  var estSec=(pw*0.015*passes+1.8*(strips2-1)+2)*cols*rows;"
"  var gpInfo=document.getElementById('gpInfo');"
"  if(gpInfo)gpInfo.innerHTML="
"    'Panels: '+(cols*rows)+' | Strips/panel: '+strips2+'<br>'"
"    +'Panel '+pw+'cm x '+ph+'cm | Est: ~'+Math.round(estSec/60)+'m '+Math.round(estSec%60)+'s';"
"}"

/* ── Joystick ── */
"(function(){"
"  var joy=document.getElementById('joy');"
"  var jh=document.getElementById('joyH');"
"  if(!joy||!jh)return;"
"  var JR=52,DEAD=12,active=false,cx=0,cy=0,lastJCmd='';"
"  function setH(dx,dy){"
"    var p=34;"
"    jh.style.left=(50+dx/JR*p)+'%';"
"    jh.style.top=(50+dy/JR*p)+'%';"
"  }"
"  function vecCmd(dx,dy){"
"    var fy=-dy,mag=Math.sqrt(dx*dx+fy*fy);"
"    if(mag<DEAD)return 'stop';"
"    var a=Math.atan2(fy,dx)*180/Math.PI;"
"    if(a>65&&a<115)return 'forward';"
"    if(a<-65&&a>-115)return 'backward';"
"    if(a>=115||a<=-115)return 'left';"
"    if(a>=-30&&a<=30)return 'right';"
"    if(a>30&&a<=65)return 'drift_right';"
"    if(a<-30&&a>=-65)return 'drift_left';"
"    return 'stop';"
"  }"
"  function onStart(e){"
"    e.preventDefault();"
"    if(autoRunning||pathPlayback)return;"
"    active=true;"
"    var r=joy.getBoundingClientRect();"
"    cx=r.left+r.width/2;"
"    cy=r.top+r.height/2;"
"    if(joy.setPointerCapture&&e.pointerId!==undefined)"
"      joy.setPointerCapture(e.pointerId);"
"  }"
"  function onMove(e){"
"    if(!active)return;"
"    e.preventDefault();"
"    var t=e.touches?e.touches[0]:e;"
"    var dx=t.clientX-cx,dy=t.clientY-cy;"
"    var m=Math.sqrt(dx*dx+dy*dy);"
"    if(m>JR){dx=dx*JR/m;dy=dy*JR/m;}"
"    setH(dx,dy);"
"    var cmd=vecCmd(dx,dy);"
"    if(cmd!==lastJCmd){lastJCmd=cmd;mv(cmd);}"
"  }"
"  function onEnd(e){"
"    if(!active)return;"
"    e.preventDefault();"
"    active=false;lastJCmd='stop';setH(0,0);mv('stop');"
"  }"
"  joy.addEventListener('pointerdown',onStart,{passive:false});"
"  joy.addEventListener('pointermove',onMove,{passive:false});"
"  joy.addEventListener('pointerup',onEnd,{passive:false});"
"  joy.addEventListener('pointercancel',onEnd,{passive:false});"
"  document.addEventListener('pointerup',onEnd,{passive:false});"
"})();"

/* ── Init ── */
"window.addEventListener('load',function(){"
"  loadGrid();"
"  pollStatus();"
"  updateServoUI(90);"
"});"

"</script>"
"</body></html>";

const char *html_get_page(void)
{
    return HTML_PAGE;
}