/*
 * html_page.c  —  Solar Panel Cleaner dashboard
 *
 * NEW vs prior version:
 *  - Path Recording panel: Record → Drive → Stop → Play
 *  - MPU heading display now shows live ±0.1° resolution
 *  - "Reset Heading" button (zeroes yaw accumulator)
 *  - Status bar shows path_recording / path_playback states
 *  - Drive panel shows REC indicator when recording
 *  - Toasts for all new path events
 */

#include "html_page.h"

static const char HTML_PAGE[] =

"<!DOCTYPE html>"
"<html lang='en'>"
"<head>"
"<meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no'>"
"<title>Solar Panel Cleaner</title>"
"<link href='https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700;900&family=Share+Tech+Mono&display=swap' rel='stylesheet'>"
"<style>"
":root{"
"--bg:#06090f;--panel:rgba(10,16,28,0.97);--border:rgba(0,210,120,0.18);"
"--accent:#00d478;--accent2:#ff4b2b;--accent3:#00aaff;--warn:#ffcc00;"
"--text:#c8e8d8;--dim:#507060;--pump:#00cfff;--blow:#ff9900;"
"--good:#00d478;--bad:#ff4b2b;--idle:#334455;"
"--rec:#ff2255;"
"}"
"*{box-sizing:border-box;margin:0;padding:0;-webkit-tap-highlight-color:transparent;}"
"body{font-family:'Orbitron',sans-serif;background:var(--bg);color:var(--text);min-height:100vh;"
"background-image:"
"radial-gradient(ellipse 70% 40% at 50% -5%,rgba(0,212,120,0.08) 0%,transparent 70%),"
"repeating-linear-gradient(0deg,transparent,transparent 39px,rgba(0,210,120,0.025) 40px),"
"repeating-linear-gradient(90deg,transparent,transparent 39px,rgba(0,210,120,0.025) 40px);}"

"header{padding:10px 16px;background:rgba(0,0,0,0.85);border-bottom:1px solid var(--border);"
"display:flex;align-items:center;justify-content:space-between;position:sticky;top:0;z-index:30;"
"backdrop-filter:blur(12px);}"
"header h1{font-size:15px;font-weight:900;letter-spacing:3px;color:var(--accent);text-shadow:0 0 14px rgba(0,212,120,0.6);}"
"header small{font-family:'Share Tech Mono';font-size:9px;color:var(--dim);}"

"#toastContainer{position:fixed;top:60px;right:12px;z-index:999;display:flex;flex-direction:column;gap:6px;pointer-events:none;}"
".toast{padding:8px 14px;border-radius:8px;font-family:'Share Tech Mono';font-size:11px;letter-spacing:1px;"
"border:1px solid;animation:toastIn 0.2s ease,toastOut 0.3s ease 3.7s forwards;pointer-events:none;}"
".toast.err{background:rgba(255,75,43,0.2);border-color:rgba(255,75,43,0.6);color:#ff6b4b;}"
".toast.warn{background:rgba(255,204,0,0.15);border-color:rgba(255,204,0,0.5);color:var(--warn);}"
".toast.ok{background:rgba(0,212,120,0.15);border-color:rgba(0,212,120,0.4);color:var(--accent);}"
".toast.rec{background:rgba(255,34,85,0.2);border-color:rgba(255,34,85,0.6);color:var(--rec);}"
"@keyframes toastIn{from{opacity:0;transform:translateX(20px)}to{opacity:1;transform:none}}"
"@keyframes toastOut{from{opacity:1}to{opacity:0}}"

"#obsBanner{display:none;margin:0 10px 8px;padding:8px 14px;border-radius:8px;"
"background:rgba(255,204,0,0.1);border:1px solid rgba(255,204,0,0.4);"
"color:var(--warn);font-weight:700;font-size:11px;text-align:center;}"

"#recBanner{display:none;margin:0 10px 8px;padding:8px 14px;border-radius:8px;"
"background:rgba(255,34,85,0.1);border:1px solid rgba(255,34,85,0.4);"
"color:var(--rec);font-weight:700;font-size:11px;text-align:center;"
"animation:blink 0.8s infinite;}"

".grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:10px;max-width:1100px;margin:0 auto;}"
"@media(max-width:640px){.grid{grid-template-columns:1fr;}}"
".panel{background:var(--panel);border:1px solid var(--border);border-radius:10px;padding:14px;"
"box-shadow:0 4px 24px rgba(0,0,0,0.6);}"
".panel h3{font-size:10px;font-weight:700;letter-spacing:3px;color:var(--accent);text-transform:uppercase;"
"margin-bottom:12px;padding-bottom:8px;border-bottom:1px solid var(--border);}"
".full{grid-column:1/-1;}"

".si{display:flex;justify-content:space-between;align-items:center;padding:4px 0;"
"border-bottom:1px solid rgba(255,255,255,0.04);font-size:11px;}"
".si:last-child{border-bottom:none;}"
".sk{color:var(--dim);font-size:9px;letter-spacing:1px;text-transform:uppercase;font-family:'Share Tech Mono';}"
".sv{font-family:'Share Tech Mono';font-size:11px;}"
".ok{color:var(--accent);}.warn2{color:var(--warn);font-weight:700;}"
".pump-on{color:var(--pump);font-weight:700;}.blow-on{color:var(--blow);font-weight:700;}"
".rec-on{color:var(--rec);font-weight:700;animation:blink 0.8s infinite;}"

".ir-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:4px;}"
".ir-cell{border:1px solid var(--border);border-radius:8px;padding:10px 8px;text-align:center;transition:all 0.2s;}"
".ir-cell .ic-label{font-size:8px;color:var(--dim);letter-spacing:2px;margin-bottom:6px;}"
".ir-cell .ic-dot{width:28px;height:28px;border-radius:50%;margin:0 auto 6px;border:2px solid var(--idle);transition:all 0.2s;}"
".ir-cell .ic-state{font-family:'Share Tech Mono';font-size:10px;color:var(--dim);}"
".ir-cell.clear .ic-dot{background:rgba(0,212,120,0.2);border-color:var(--accent);box-shadow:0 0 8px rgba(0,212,120,0.4);}"
".ir-cell.clear .ic-state{color:var(--accent);}"
".ir-cell.blocked .ic-dot{background:rgba(255,75,43,0.3);border-color:var(--accent2);box-shadow:0 0 12px rgba(255,75,43,0.6);}"
".ir-cell.blocked .ic-state{color:var(--accent2);font-weight:700;}"
".ir-status-row{display:flex;justify-content:space-between;margin-top:10px;padding-top:10px;"
"border-top:1px solid var(--border);font-family:'Share Tech Mono';font-size:9px;}"
".ir-zone{text-align:center;}"
".iz-label{color:var(--dim);letter-spacing:1px;margin-bottom:3px;}"
".iz-val{font-size:12px;font-weight:700;}"

".mpu-ready-badge{display:inline-block;padding:3px 10px;border-radius:12px;font-size:9px;letter-spacing:2px;margin-bottom:10px;}"
".mpu-ready-badge.ok{background:rgba(0,212,120,0.15);border:1px solid rgba(0,212,120,0.4);color:var(--accent);}"
".mpu-ready-badge.fail{background:rgba(255,75,43,0.15);border:1px solid rgba(255,75,43,0.4);color:var(--accent2);}"
".mpu-row{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px;}"

".compass-wrap{display:flex;flex-direction:column;align-items:center;gap:4px;}"
".compass{position:relative;width:80px;height:80px;border-radius:50%;"
"background:radial-gradient(circle,#0a1a14 0,#040c08 100%);"
"border:2px solid rgba(0,212,120,0.3);}"
".compass-ring{position:absolute;inset:4px;border-radius:50%;border:1px solid rgba(0,212,120,0.1);}"
".compass-n{position:absolute;top:4px;left:50%;transform:translateX(-50%);font-size:8px;color:var(--accent2);font-weight:700;}"
".compass-s{position:absolute;bottom:4px;left:50%;transform:translateX(-50%);font-size:7px;color:var(--dim);}"
".compass-e{position:absolute;right:4px;top:50%;transform:translateY(-50%);font-size:7px;color:var(--dim);}"
".compass-w{position:absolute;left:4px;top:50%;transform:translateY(-50%);font-size:7px;color:var(--dim);}"
".compass-needle{position:absolute;left:50%;top:50%;width:2px;height:28px;margin-left:-1px;margin-top:-28px;"
"background:linear-gradient(var(--accent2) 0%,transparent 100%);"
"transform-origin:bottom center;border-radius:2px 2px 0 0;transition:transform 0.15s linear;}"
".compass-dot{position:absolute;left:50%;top:50%;width:6px;height:6px;border-radius:50%;"
"background:var(--accent);transform:translate(-50%,-50%);box-shadow:0 0 6px var(--accent);}"
".compass-hdg{font-family:'Share Tech Mono';font-size:14px;color:var(--accent);letter-spacing:1px;}"
".compass-gz{font-family:'Share Tech Mono';font-size:9px;color:var(--dim);margin-top:2px;}"

".tilt-wrap{display:flex;flex-direction:column;align-items:center;gap:4px;}"
".tilt-plate{position:relative;width:80px;height:80px;border-radius:50%;"
"background:radial-gradient(circle,#0a1420 0,#050a10 100%);"
"border:2px solid rgba(0,170,255,0.3);overflow:hidden;}"
".tilt-cross-h{position:absolute;left:0;right:0;top:50%;height:1px;background:rgba(0,170,255,0.15);}"
".tilt-cross-v{position:absolute;top:0;bottom:0;left:50%;width:1px;background:rgba(0,170,255,0.15);}"
".tilt-ring{position:absolute;inset:18px;border-radius:50%;border:1px solid rgba(0,170,255,0.2);}"
".tilt-bubble{position:absolute;width:14px;height:14px;border-radius:50%;"
"background:radial-gradient(circle at 35% 35%,rgba(0,170,255,0.9),rgba(0,100,200,0.5));"
"border:1px solid rgba(0,200,255,0.8);box-shadow:0 0 8px rgba(0,170,255,0.5);"
"left:50%;top:50%;transform:translate(-50%,-50%);transition:left 0.15s,top 0.15s;}"
".tilt-label{font-family:'Share Tech Mono';font-size:9px;color:var(--accent3);letter-spacing:1px;}"

".accel-bars{margin-top:8px;}"
".ab-row{display:flex;align-items:center;gap:6px;margin:3px 0;}"
".ab-axis{font-family:'Share Tech Mono';font-size:9px;color:var(--dim);width:14px;text-align:right;}"
".ab-track{flex:1;height:6px;background:rgba(255,255,255,0.05);border-radius:3px;overflow:hidden;position:relative;}"
".ab-center{position:absolute;left:50%;top:0;bottom:0;width:1px;background:rgba(255,255,255,0.15);}"
".ab-fill{position:absolute;height:100%;border-radius:3px;transition:left 0.15s,width 0.15s;}"
".ab-fill.ax{background:rgba(255,75,43,0.7);}"
".ab-fill.ay{background:rgba(0,212,120,0.7);}"
".ab-fill.az{background:rgba(0,170,255,0.7);}"
".ab-val{font-family:'Share Tech Mono';font-size:9px;color:var(--text);width:42px;text-align:right;}"

".vib-meter{margin-top:8px;}"
".vib-track{height:10px;background:rgba(255,255,255,0.05);border-radius:5px;overflow:hidden;}"
".vib-fill{height:100%;border-radius:5px;transition:width 0.2s,background 0.2s;background:var(--accent);}"
".vib-labels{display:flex;justify-content:space-between;font-family:'Share Tech Mono';font-size:8px;color:var(--dim);margin-top:2px;}"

".btn{padding:8px 10px;margin:2px;font-family:'Orbitron',sans-serif;font-size:9px;"
"font-weight:700;letter-spacing:1px;border:1px solid rgba(255,255,255,0.1);border-radius:6px;"
"cursor:pointer;transition:all 0.12s;text-transform:uppercase;user-select:none;"
"touch-action:manipulation;background:rgba(255,255,255,0.04);color:var(--text);}"
".btn:active{transform:scale(0.95);}"
".btn:disabled,.btn.disabled{opacity:0.35;cursor:not-allowed;}"
".btn.dir{background:rgba(0,212,120,0.08);color:var(--accent);border-color:rgba(0,212,120,0.25);}"
".btn.stop-btn{background:rgba(255,75,43,0.1);color:var(--accent2);border-color:rgba(255,75,43,0.35);}"
".btn.tail{background:rgba(255,204,0,0.08);color:var(--warn);border-color:rgba(255,204,0,0.25);}"
".btn.rst{background:rgba(0,170,255,0.08);color:var(--accent3);border-color:rgba(0,170,255,0.25);}"
".btn.active{box-shadow:0 0 12px rgba(0,212,120,0.5);background:rgba(0,212,120,0.2);}"
".btn.rec-btn{background:rgba(255,34,85,0.12);color:var(--rec);border-color:rgba(255,34,85,0.4);}"
".btn.rec-btn.recording{background:rgba(255,34,85,0.3);box-shadow:0 0 16px rgba(255,34,85,0.5);animation:blink 0.8s infinite;}"
".btn.play-btn{background:rgba(0,212,120,0.12);color:var(--accent);border-color:rgba(0,212,120,0.4);}"
".btn.auto-btn{background:rgba(0,212,120,0.12);color:var(--accent);border-color:rgba(0,212,120,0.4);"
"width:100%;padding:10px;margin-top:8px;letter-spacing:2px;}"
".btn.stop-auto{background:rgba(255,75,43,0.12);color:var(--accent2);border-color:rgba(255,75,43,0.4);"
"width:100%;padding:10px;margin-top:6px;}"
".btn.chk-btn{background:rgba(0,170,255,0.08);color:var(--accent3);border-color:rgba(0,170,255,0.3);"
"width:100%;padding:9px;margin-top:8px;}"

"@keyframes blink{0%,100%{opacity:1}50%{opacity:0.4}}"

".jw{display:flex;justify-content:center;margin:8px 0;}"
".joystick{width:140px;height:140px;border-radius:50%;"
"background:radial-gradient(circle at 30% 30%,#162030 0,#050810 60%);"
"border:1px solid var(--border);position:relative;"
"box-shadow:0 8px 20px rgba(0,0,0,0.8),0 0 16px rgba(0,212,120,0.05) inset;touch-action:none;}"
".joy-h{width:48px;height:48px;border-radius:50%;"
"background:radial-gradient(circle at 30% 30%,#2a4a38 0,#0a1a14 60%);"
"position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);"
"box-shadow:0 0 10px rgba(0,212,120,0.3),0 4px 8px rgba(0,0,0,0.8);"
"transition:left 0.04s,top 0.04s;pointer-events:none;}"
".jlbl{font-size:8px;color:var(--dim);text-align:center;margin-top:4px;letter-spacing:2px;}"
".bgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:3px;margin-top:8px;}"
".bgrid .btn{padding:6px 2px;font-size:8px;}"

".prow{display:flex;gap:8px;margin-top:10px;padding-top:10px;border-top:1px solid var(--border);}"
".pbtn{flex:1;padding:10px 4px;border-radius:6px;border:1px solid;cursor:pointer;"
"font-family:'Orbitron',sans-serif;font-size:9px;font-weight:700;letter-spacing:1px;text-align:center;transition:all 0.15s;}"
".pbtn-pump{background:rgba(0,207,255,0.06);color:var(--pump);border-color:rgba(0,207,255,0.3);}"
".pbtn-pump.pon{background:rgba(0,207,255,0.2);box-shadow:0 0 14px rgba(0,207,255,0.4);}"
".pbtn-blow{background:rgba(255,153,0,0.06);color:var(--blow);border-color:rgba(255,153,0,0.3);}"
".pbtn-blow.bon{background:rgba(255,153,0,0.2);box-shadow:0 0 14px rgba(255,153,0,0.4);}"

".lcd{background:#060f06;border:2px solid #1a4a1a;border-radius:6px;padding:7px 10px;"
"font-family:'Share Tech Mono';font-size:12px;color:#33ff66;"
"text-shadow:0 0 6px rgba(0,255,80,0.5);box-shadow:0 0 10px rgba(0,80,0,0.4) inset;"
"letter-spacing:1px;margin-top:8px;}"
".ll{height:18px;white-space:pre;overflow:hidden;}"
".ld{border-top:1px solid #1a3a1a;margin:3px 0;}"

"#pingDot{width:8px;height:8px;border-radius:50%;background:#444;display:inline-block;margin-left:6px;transition:background 0.3s;}"
"#pingDot.ok{background:var(--accent);box-shadow:0 0 6px var(--accent);}"
"#pingDot.err{background:var(--accent2);}"

".auto-box{margin-top:10px;padding:12px;border-radius:8px;border:1px solid var(--border);"
"background:rgba(0,0,0,0.3);}"
".auto-state-label{font-size:10px;font-weight:700;letter-spacing:3px;margin-bottom:8px;}"
".auto-state-label.idle{color:var(--dim);}"
".auto-state-label.running{color:var(--accent);animation:blink 1.2s infinite;}"
".auto-state-label.done{color:var(--accent3);}"
".auto-state-label.error{color:var(--accent2);}"
".progress-track{height:12px;background:rgba(255,255,255,0.05);border-radius:6px;overflow:hidden;margin:6px 0;}"
".progress-fill{height:100%;border-radius:6px;background:linear-gradient(90deg,#00a058,#00d478);"
"transition:width 0.5s ease;}"
".progress-labels{display:flex;justify-content:space-between;font-family:'Share Tech Mono';font-size:9px;color:var(--dim);}"

/* path panel */
".path-panel{border:1px solid rgba(255,34,85,0.25);border-radius:8px;padding:12px;margin-top:10px;"
"background:rgba(255,34,85,0.04);}"
".path-panel h4{font-size:10px;font-weight:700;letter-spacing:3px;color:var(--rec);"
"text-transform:uppercase;margin-bottom:10px;}"
".path-status{font-family:'Share Tech Mono';font-size:10px;margin-bottom:8px;padding:6px 10px;"
"border-radius:6px;background:rgba(0,0,0,0.4);border:1px solid rgba(255,255,255,0.06);}"
".path-row{display:flex;gap:6px;flex-wrap:wrap;}"
".path-count{font-family:'Share Tech Mono';font-size:9px;color:var(--dim);margin-top:8px;}"
".path-count span{color:var(--accent3);}"

".chk-table{width:100%;border-collapse:collapse;font-family:'Share Tech Mono';font-size:10px;margin-top:8px;}"
".chk-table th{color:var(--dim);font-size:8px;letter-spacing:2px;text-align:left;padding:3px 6px;"
"border-bottom:1px solid var(--border);}"
".chk-table td{padding:5px 6px;border-bottom:1px solid rgba(255,255,255,0.04);}"
".chk-ok{color:var(--accent);}.chk-fail{color:var(--accent2);font-weight:700;}.chk-na{color:var(--dim);}"

".ge-row{display:flex;align-items:center;gap:8px;margin:5px 0;}"
".ge-label{font-family:'Share Tech Mono';font-size:9px;color:var(--dim);width:110px;letter-spacing:1px;}"
".ge-input{flex:1;background:rgba(0,0,0,0.5);border:1px solid var(--border);border-radius:4px;"
"color:var(--accent);font-family:'Share Tech Mono';font-size:12px;padding:4px 8px;text-align:center;}"
".ge-input:focus{outline:none;border-color:var(--accent);}"
".ge-check{display:flex;align-items:center;gap:6px;cursor:pointer;font-family:'Share Tech Mono';font-size:9px;color:var(--dim);}"
".ge-check input{accent-color:var(--accent);width:14px;height:14px;}"
"#gridPreview{margin-top:10px;padding:8px;background:rgba(0,0,0,0.4);"
"border:1px solid rgba(0,212,120,0.12);border-radius:6px;display:flex;justify-content:center;}"
".brow{display:flex;flex-wrap:wrap;gap:4px;margin-top:8px;}"
"</style>"
"</head>"
"<body>"

"<div id='toastContainer'></div>"
"<header>"
"<div><h1>&#9728; SOLAR CLEANER <span id='pingDot'></span></h1></div>"
"<small>AP: SolarCleaner &nbsp;|&nbsp; 192.168.4.1</small>"
"</header>"
"<div id='obsBanner'>&#128680; OBSTACLE DETECTED &mdash; PATH BLOCKED</div>"
"<div id='recBanner'>&#9679; PATH RECORDING ACTIVE &mdash; DRIVE THE ROVER NOW</div>"

"<div class='grid'>"

/* ══ DRIVE PANEL ══ */
"<div class='panel'>"
"<h3>&#127918; Manual Drive <span id='recIndicator' style='display:none;color:var(--rec);font-size:8px;letter-spacing:2px;animation:blink 0.8s infinite'>&#9679; REC</span></h3>"
"<div id='autoLockMsg' style='display:none;padding:8px;background:rgba(0,212,120,0.1);border:1px solid rgba(0,212,120,0.3);"
"border-radius:6px;font-family:\"Share Tech Mono\";font-size:9px;color:var(--accent);text-align:center;margin-bottom:8px;'>"
"&#9888; AUTO-CLEAN RUNNING &mdash; MANUAL DRIVE LOCKED"
"</div>"
"<div class='jw'><div class='joystick' id='joy'><div class='joy-h' id='joyH'></div></div></div>"
"<div class='jlbl'>DRAG TO DRIVE &bull; RELEASE = STOP</div>"
"<div class='bgrid'>"
"<button class='btn dir' id='bDL'  onpointerdown=\"mv('drift_left')\">DFT-L</button>"
"<button class='btn dir' id='bFWD' onpointerdown=\"mv('forward')\">&#9650; FWD</button>"
"<button class='btn dir' id='bDR'  onpointerdown=\"mv('drift_right')\">DFT-R</button>"
"<button class='btn dir' id='bL'   onpointerdown=\"mv('left')\">&#9668; LEFT</button>"
"<button class='btn stop-btn' id='bSTOP' onpointerdown=\"mv('stop')\">&#9632; STP</button>"
"<button class='btn dir' id='bR'   onpointerdown=\"mv('right')\">RIGHT &#9658;</button>"
"<div></div>"
"<button class='btn dir' id='bBWD' onpointerdown=\"mv('backward')\">&#9660; BWD</button>"
"<div></div>"
"</div>"
"<div class='prow'>"
"<div class='pbtn pbtn-pump' id='bPump' onclick='togglePump()'>&#128166; PUMP<br><span id='sPumpLbl'>OFF</span></div>"
"<div class='pbtn pbtn-blow' id='bBlow' onclick='toggleBlow()'>&#127756; BLOWER<br><span id='sBlowLbl'>OFF</span></div>"
"</div>"
"</div>"

/* ══ PATH RECORDING PANEL ══ */
"<div class='panel'>"
"<h3>&#127936; Path Record &amp; Replay</h3>"
"<div style='font-size:9px;color:var(--dim);font-family:\"Share Tech Mono\";line-height:1.8;margin-bottom:10px;'>"
"1&#41; Press <span style='color:var(--rec)'>START REC</span> &rarr; drive rover over one panel<br>"
"2&#41; Press <span style='color:var(--warn)'>STOP REC</span> when done with one panel<br>"
"3&#41; Place rover at start &rarr; press <span style='color:var(--accent)'>PLAY PATH</span><br>"
"Rover repeats your exact moves on every panel automatically."
"</div>"
"<div class='path-status'>"
"<div style='display:flex;justify-content:space-between;align-items:center;'>"
"<span id='pathStateLabel' style='color:var(--dim);font-size:9px;letter-spacing:2px;'>IDLE</span>"
"<span id='pathStepsLabel' style='color:var(--accent3);'>0 steps</span>"
"</div>"
"<div style='margin-top:6px;'>"
"<div id='pathProgBar' style='height:4px;background:rgba(255,255,255,0.05);border-radius:2px;overflow:hidden;'>"
"<div id='pathProgFill' style='height:100%;width:0%;background:var(--rec);transition:width 0.3s;border-radius:2px;'></div>"
"</div>"
"</div>"
"</div>"
"<div class='path-row'>"
"<button class='btn rec-btn' id='btnRecStart' onclick='pathRecStart()' style='flex:1;padding:10px 4px;'>&#9679; START REC</button>"
"<button class='btn' id='btnRecStop' onclick='pathRecStop()' style='flex:1;padding:10px 4px;background:rgba(255,204,0,0.1);color:var(--warn);border-color:rgba(255,204,0,0.4);'>&#9632; STOP REC</button>"
"</div>"
"<div class='path-row' style='margin-top:6px;'>"
"<button class='btn play-btn' id='btnPathPlay' onclick='pathPlay()' style='flex:1;padding:10px 4px;'>&#9654; PLAY PATH</button>"
"<button class='btn stop-btn' id='btnPathStop' onclick='stopAuto()' style='flex:1;padding:10px 4px;'>&#9632; STOP</button>"
"<button class='btn' id='btnPathClear' onclick='pathClear()' style='flex:1;padding:10px 4px;background:rgba(120,120,120,0.08);color:var(--dim);border-color:rgba(120,120,120,0.2);font-size:8px;'>&#128465; CLEAR</button>"
"</div>"
"<div style='margin-top:10px;padding:8px;border-radius:6px;border:1px solid rgba(0,170,255,0.15);"
"background:rgba(0,170,255,0.04);font-family:\"Share Tech Mono\";font-size:8px;color:var(--dim);line-height:1.8;'>"
"<div style='color:var(--accent3);font-size:9px;margin-bottom:4px;'>HOW IT WORKS</div>"
"Every joystick/button input, pump, and blower toggle is timestamped<br>"
"and stored. Playback replays each segment at exactly the same speed.<br>"
"Up to 256 segments can be stored (cleared on power cycle)."
"</div>"
"</div>"

/* ══ IR SENSORS ══ */
"<div class='panel'>"
"<h3>&#128064; IR Obstacle Sensors</h3>"
"<div style='font-size:9px;color:var(--dim);font-family:\"Share Tech Mono\";letter-spacing:1px;margin-bottom:8px;'>"
"Digital sensors -- LOW = obstacle (active-LOW with pull-up)"
"</div>"
"<div class='ir-grid'>"
"<div class='ir-cell' id='irFL'><div class='ic-label'>FRONT LEFT</div><div class='ic-dot'></div><div class='ic-state' id='irFLst'>---</div></div>"
"<div class='ir-cell' id='irFR'><div class='ic-label'>FRONT RIGHT</div><div class='ic-dot'></div><div class='ic-state' id='irFRst'>---</div></div>"
"<div class='ir-cell' id='irBL'><div class='ic-label'>BACK LEFT</div><div class='ic-dot'></div><div class='ic-state' id='irBLst'>---</div></div>"
"<div class='ir-cell' id='irBR'><div class='ic-label'>BACK RIGHT</div><div class='ic-dot'></div><div class='ic-state' id='irBRst'>---</div></div>"
"</div>"
"<div class='ir-status-row'>"
"<div class='ir-zone'><div class='iz-label'>FRONT ZONE</div><div class='iz-val' id='izF' style='color:var(--dim)'>CLEAR</div></div>"
"<div class='ir-zone'><div class='iz-label'>BACK ZONE</div><div class='iz-val' id='izB' style='color:var(--dim)'>CLEAR</div></div>"
"</div>"
"<div class='lcd'>"
"<div class='ll' id='l1'>Dir: STOP       </div>"
"<div class='ld'></div>"
"<div class='ll' id='l2'>F:CLR  B:CLR    </div>"
"</div>"
"</div>"

/* ══ MPU-6050 ══ */
"<div class='panel'>"
"<h3>&#129517; MPU-6050 IMU</h3>"
"<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;'>"
"<div id='mpuBadge' class='mpu-ready-badge fail'>NOT DETECTED</div>"
"<button class='btn rst' onclick='resetHeading()' style='padding:4px 10px;font-size:8px;'>&#9654; ZERO HDG</button>"
"</div>"
"<div class='mpu-row'>"
"<div class='compass-wrap'>"
"<div class='compass'>"
"<div class='compass-ring'></div>"
"<div class='compass-n'>N</div><div class='compass-s'>S</div>"
"<div class='compass-e'>E</div><div class='compass-w'>W</div>"
"<div class='compass-needle' id='cNeedle'></div>"
"<div class='compass-dot'></div>"
"</div>"
"<div class='compass-hdg' id='cHdg'>0.00&deg;</div>"
"<div class='compass-gz' id='cGz'>Gz: 0.000 &deg;/s</div>"
"</div>"
"<div class='tilt-wrap'>"
"<div class='tilt-plate'>"
"<div class='tilt-cross-h'></div><div class='tilt-cross-v'></div>"
"<div class='tilt-ring'></div>"
"<div class='tilt-bubble' id='tBubble'></div>"
"</div>"
"<div class='tilt-label'>TILT / ACCEL</div>"
"</div>"
"</div>"
"<div class='accel-bars'>"
"<div style='font-size:8px;color:var(--dim);font-family:\"Share Tech Mono\";letter-spacing:2px;margin-bottom:4px;'>ACCELEROMETER (g)</div>"
"<div class='ab-row'><span class='ab-axis' style='color:#ff4b2b'>X</span><div class='ab-track'><div class='ab-center'></div><div class='ab-fill ax' id='abX' style='left:50%;width:0'></div></div><span class='ab-val' id='avX'>0.000</span></div>"
"<div class='ab-row'><span class='ab-axis' style='color:#00d478'>Y</span><div class='ab-track'><div class='ab-center'></div><div class='ab-fill ay' id='abY' style='left:50%;width:0'></div></div><span class='ab-val' id='avY'>0.000</span></div>"
"<div class='ab-row'><span class='ab-axis' style='color:#00aaff'>Z</span><div class='ab-track'><div class='ab-center'></div><div class='ab-fill az' id='abZ' style='left:50%;width:0'></div></div><span class='ab-val' id='avZ'>1.000</span></div>"
"</div>"
"<div class='vib-meter'>"
"<div style='display:flex;justify-content:space-between;font-size:8px;font-family:\"Share Tech Mono\";color:var(--dim);margin-bottom:3px;'>"
"<span>VIBRATION</span><span id='vibVal'>0.000 g</span></div>"
"<div class='vib-track'><div class='vib-fill' id='vibFill' style='width:0'></div></div>"
"<div class='vib-labels'><span>0</span><span>0.5g</span><span>2g</span></div>"
"</div>"
"<div class='si' style='margin-top:8px'><span class='sk'>Temp</span><span class='sv' id='mpuTemp'>---</span></div>"
"</div>"

/* ══ STATUS ══ */
"<div class='panel'>"
"<h3>&#128202; System Status</h3>"
"<div class='si'><span class='sk'>Direction</span><span class='sv' id='sDir'>&mdash;</span></div>"
"<div class='si'><span class='sk'>Heading</span><span class='sv' id='sHdg'>&mdash;</span></div>"
"<div class='si'><span class='sk'>Gyro Z</span><span class='sv' id='sGz'>&mdash;</span></div>"
"<div class='si'><span class='sk'>Tail Light</span><span class='sv' id='sTail'>&mdash;</span></div>"
"<div class='si'><span class='sk'>Vibration</span><span class='sv' id='sVib'>&mdash;</span></div>"
"<div class='si'><span class='sk'>Front Blocked</span><span class='sv' id='sFObs'>&mdash;</span></div>"
"<div class='si'><span class='sk'>Back Blocked</span><span class='sv' id='sBObs'>&mdash;</span></div>"
"<div class='si'><span class='sk'>Water Pump</span><span class='sv' id='sPumpSt'>&mdash;</span></div>"
"<div class='si'><span class='sk'>Air Blower</span><span class='sv' id='sBlowSt'>&mdash;</span></div>"
"<div class='si'><span class='sk'>Auto State</span><span class='sv' id='sAutoSt'>&mdash;</span></div>"
"<div class='si'><span class='sk'>Path</span><span class='sv' id='sPathSt'>&mdash;</span></div>"
"<div class='si'><span class='sk'>Ping</span><span class='sv' id='sPing'>&mdash;</span></div>"
"<div style='margin-top:10px;padding-top:10px;border-top:1px solid var(--border);'>"
"<div style='font-size:9px;color:var(--dim);letter-spacing:2px;margin-bottom:8px;font-family:\"Share Tech Mono\"'>CONTROLS</div>"
"<div class='brow'>"
"<button class='btn tail' onclick=\"setTail(1)\">TAIL ON</button>"
"<button class='btn tail' onclick=\"setTail(0)\">TAIL OFF</button>"
"</div>"
"<button class='btn' id='bRAM' onclick='toggleRam()' style='width:100%;margin-top:8px;background:rgba(255,51,0,0.08);color:#ff4400;border-color:rgba(255,51,0,0.3);'>&#128165; RAMMING: OFF</button>"
"</div>"
"</div>"

/* ══ SENSOR DIAGNOSTIC ══ */
"<div class='panel'>"
"<h3>&#128295; Sensor Wiring Check</h3>"
"<div style='font-size:9px;color:var(--dim);font-family:\"Share Tech Mono\";line-height:1.6;'>"
"IR: clear area = CLEAR expected.<br>"
"MPU: flat surface = Ax~0 Ay~0 Az~1.0<br>"
"Rover: <span id='roverDims' style='color:var(--accent3)'>---</span>"
"</div>"
"<button class='btn chk-btn' onclick='runSensorCheck()'>&#9654; RUN SENSOR CHECK</button>"
"<div id='chkResult' style='margin-top:8px;'></div>"
"</div>"

/* ══ GRID EDITOR (full width) ══ */
"<div class='panel full'>"
"<h3>&#9728; Solar Panel Grid &amp; Auto Clean</h3>"
"<div style='display:grid;grid-template-columns:1fr 1fr;gap:16px;'>"
"<div>"
"<div style='font-size:9px;color:var(--dim);letter-spacing:2px;margin-bottom:8px;font-family:\"Share Tech Mono\"'>PANEL LAYOUT</div>"
"<div class='ge-row'><span class='ge-label'>COLUMNS</span><input class='ge-input' type='number' id='gCols' value='2' min='1' max='10'></div>"
"<div class='ge-row'><span class='ge-label'>ROWS</span><input class='ge-input' type='number' id='gRows' value='1' min='1' max='10'></div>"
"<div class='ge-row'><span class='ge-label'>PANEL WIDTH (cm)</span><input class='ge-input' type='number' id='gPW' value='200' min='20' max='600'></div>"
"<div class='ge-row'><span class='ge-label'>PANEL HEIGHT (cm)</span><input class='ge-input' type='number' id='gPH' value='170' min='20' max='600'></div>"
"<div class='ge-row'><span class='ge-label'>GAP BETWEEN (cm)</span><input class='ge-input' type='number' id='gGap' value='5' min='0' max='200'></div>"
"<div style='margin-top:8px;display:flex;gap:8px;flex-wrap:wrap;'>"
"<label class='ge-check'><input type='checkbox' id='gWash' checked> &#128166; Pump during clean</label>"
"<label class='ge-check'><input type='checkbox' id='gBlow'> &#127756; Blower during clean</label>"
"</div>"
"<div id='calcInfo' style='margin-top:10px;padding:8px;background:rgba(0,170,255,0.05);"
"border:1px solid rgba(0,170,255,0.15);border-radius:6px;font-family:\"Share Tech Mono\";font-size:9px;'></div>"
"<div style='display:flex;gap:6px;margin-top:10px;'>"
"<button class='btn rst' onclick='saveGrid()' style='flex:1'>SAVE GRID</button>"
"</div>"
"<div id='gridMsg' style='font-family:\"Share Tech Mono\";font-size:9px;color:var(--accent);margin-top:6px;min-height:14px;'></div>"

"<div class='auto-box'>"
"<div class='auto-state-label idle' id='autoStateLabel'>IDLE &mdash; READY TO CLEAN</div>"
"<div class='progress-track'><div class='progress-fill' id='progressFill' style='width:0'></div></div>"
"<div class='progress-labels'>"
"<span id='stripsDone'>0 strips done</span>"
"<span id='progressPct'>0%</span>"
"<span id='stripsTotal'>/ 0 total</span>"
"</div>"
"</div>"
"<button class='btn auto-btn' id='startAutoBtn' onclick='startAuto()'>&#9654; START AUTO CLEAN</button>"
"<button class='btn stop-auto' id='stopAutoBtn' onclick='stopAuto()' style='display:none'>&#9632; STOP AUTO CLEAN</button>"
"</div>"

"<div>"
"<div style='font-size:9px;color:var(--dim);letter-spacing:2px;margin-bottom:8px;font-family:\"Share Tech Mono\"'>PATTERN PREVIEW</div>"
"<div id='gridPreview'><canvas id='gpCanvas' width='280' height='200'></canvas></div>"
"<div id='gpInfo' style='font-family:\"Share Tech Mono\";font-size:9px;color:var(--dim);margin-top:6px;line-height:1.6;'></div>"
"<div style='margin-top:8px;padding:8px;background:rgba(0,0,0,0.3);border-radius:6px;"
"font-family:\"Share Tech Mono\";font-size:8px;color:var(--dim);line-height:1.8;'>"
"<div style='color:var(--accent);font-size:9px;margin-bottom:4px;'>PATTERN LEGEND</div>"
"<div>&#9660; Green arrows = FORWARD sweep (gyro-guided)</div>"
"<div>&#9650; Grey arrows  = lateral step turn sequence</div>"
"<div>&#9658; Blue arrow   = inter-panel advance</div>"
"<div>&#9733; Yellow dot   = start position (top-left)</div>"
"</div>"
"</div>"
"</div>"
"</div>"

"</div>"

/* ════════════════ JAVASCRIPT ════════════════ */
"<script>"

"function toast(msg,type){"
"  var c=document.getElementById('toastContainer');"
"  var t=document.createElement('div');"
"  t.className='toast '+(type||'ok');"
"  t.textContent=msg;"
"  c.appendChild(t);"
"  setTimeout(function(){if(t.parentNode)t.parentNode.removeChild(t);},4200);"
"}"

"var lastFB=0,lastBB=0,ramOn=0,pumpOn=0,blowOn=0;"
"var lastCmd='',inFlight=0,pendingCmd=null;"
"var autoRunning=false,lastAutoRunning=false;"
"var pathRecording=false,lastPathRecording=false;"
"var pathPlayback=false,lastPathPlayback=false;"
"var pathSteps=0;"

/* ── Move ── */
"function mv(dir){"
"  if(autoRunning||pathPlayback)return;"
"  if(dir===lastCmd&&dir!=='stop')return;"
"  if(inFlight>0){pendingCmd=dir;return;}"
"  sendMove(dir);"
"}"
"function sendMove(dir){"
"  lastCmd=dir;inFlight++;hiBtn(dir);"
"  fetch('/move?dir='+dir,{method:'GET',keepalive:true})"
"    .then(function(r){return r.text();})"
"    .then(function(t){inFlight--;flushPending();"
"      if(t.indexOf('BLOCKED')===0)toast(t,'warn');"
"    })"
"    .catch(function(){inFlight--;flushPending();});"
"}"
"function flushPending(){"
"  if(pendingCmd!==null){var c=pendingCmd;pendingCmd=null;sendMove(c);}"
"}"
"function hiBtn(dir){"
"  var map={forward:'bFWD',backward:'bBWD',left:'bL',right:'bR',drift_left:'bDL',drift_right:'bDR',stop:'bSTOP'};"
"  ['bFWD','bBWD','bL','bR','bDL','bDR','bSTOP'].forEach(function(id){"
"    var el=document.getElementById(id);if(el)el.classList.remove('active');"
"  });"
"  var id=map[dir];if(id){var el=document.getElementById(id);if(el)el.classList.add('active');}"
"}"

"function setTail(s){fetch('/tail?state='+(s?'on':'off')).then(function(r){return r.text();}).then(function(t){toast(t,'ok');}).catch(function(){});}"

"function togglePump(){"
"  pumpOn=!pumpOn;"
"  fetch('/pump?state='+(pumpOn?'on':'off')).catch(function(){});"
"  updatePumpUI();"
"}"
"function toggleBlow(){"
"  blowOn=!blowOn;"
"  fetch('/blower?state='+(blowOn?'on':'off')).catch(function(){});"
"  updateBlowUI();"
"}"
"function updatePumpUI(){"
"  var b=document.getElementById('bPump'),l=document.getElementById('sPumpLbl'),s=document.getElementById('sPumpSt');"
"  if(pumpOn){b.classList.add('pon');l.textContent='ON';if(s){s.textContent='ON';s.className='sv pump-on';}}"
"  else{b.classList.remove('pon');l.textContent='OFF';if(s){s.textContent='OFF';s.className='sv ok';}}"
"}"
"function updateBlowUI(){"
"  var b=document.getElementById('bBlow'),l=document.getElementById('sBlowLbl'),s=document.getElementById('sBlowSt');"
"  if(blowOn){b.classList.add('bon');l.textContent='ON';if(s){s.textContent='ON';s.className='sv blow-on';}}"
"  else{b.classList.remove('bon');l.textContent='OFF';if(s){s.textContent='OFF';s.className='sv ok';}}"
"}"
"function toggleRam(){"
"  ramOn=!ramOn;"
"  fetch('/ramming?state='+(ramOn?'on':'off')).catch(function(){});"
"  updateRamUI();"
"}"
"function updateRamUI(){"
"  var b=document.getElementById('bRAM');"
"  if(ramOn){b.textContent='RAMMING: ON';b.style.background='rgba(255,51,0,0.3)';b.style.boxShadow='0 0 14px rgba(255,51,0,0.6)';}"
"  else{b.textContent='RAMMING: OFF';b.style.background='rgba(255,51,0,0.08)';b.style.boxShadow='none';}"
"}"

"function resetHeading(){"
"  fetch('/mpu_reset').then(function(r){return r.text();}).then(function(t){toast('Heading zeroed','ok');}).catch(function(){});"
"}"

/* ── Path recording ── */
"function pathRecStart(){"
"  fetch('/path_record_start').then(function(r){return r.text();})"
"  .then(function(t){"
"    if(t==='RECORDING_STARTED'){toast('&#9679; Recording started — drive now!','rec');}"
"    else{toast(t,'warn');}"
"  }).catch(function(){toast('Request failed','err');});"
"}"
"function pathRecStop(){"
"  fetch('/path_record_stop').then(function(r){return r.text();})"
"  .then(function(t){toast(t,'ok');}).catch(function(){toast('Request failed','err');});"
"}"
"function pathPlay(){"
"  if(pathSteps===0){toast('No path recorded yet','warn');return;}"
"  if(!confirm('Play back the recorded path?\\n\\nPlace rover at the START POSITION first!'))return;"
"  fetch('/path_play').then(function(r){return r.text();})"
"  .then(function(t){"
"    if(t==='PLAYBACK_STARTED'){toast('&#9654; Playback started','ok');}"
"    else{toast(t,'warn');}"
"  }).catch(function(){toast('Request failed','err');});"
"}"
"function pathClear(){"
"  if(pathSteps>0&&!confirm('Clear the recorded path ('+pathSteps+' steps)?'))return;"
"  fetch('/path_clear').then(function(r){return r.text();})"
"  .then(function(t){toast(t,'ok');}).catch(function(){});"
"}"

"function updatePathUI(d){"
"  var rec=!!d.path_recording;"
"  var play=!!d.path_playback;"
"  var steps=d.path_steps||0;"
"  pathRecording=rec;pathPlayback=play;pathSteps=steps;"

"  var stLabel=document.getElementById('pathStateLabel');"
"  var stSteps=document.getElementById('pathStepsLabel');"
"  var recInd=document.getElementById('recIndicator');"
"  var recBanner=document.getElementById('recBanner');"
"  var progFill=document.getElementById('pathProgFill');"

"  if(stLabel)stLabel.textContent=rec?'RECORDING':play?'PLAYING BACK':'IDLE';"
"  if(stLabel)stLabel.style.color=rec?'var(--rec)':play?'var(--accent)':'var(--dim)';"
"  if(stSteps)stSteps.textContent=steps+' steps';"
"  if(recInd)recInd.style.display=rec?'inline':'none';"
"  if(recBanner)recBanner.style.display=rec?'block':'none';"

"  var maxSteps=256;"
"  if(progFill){progFill.style.width=(steps/maxSteps*100)+'%';"
"    progFill.style.background=rec?'var(--rec)':play?'var(--accent)':'rgba(0,170,255,0.6)';}"

"  var sPathSt=document.getElementById('sPathSt');"
"  if(sPathSt){"
"    if(rec){sPathSt.textContent='REC ('+steps+')';sPathSt.className='sv rec-on';}"
"    else if(play){sPathSt.textContent='PLAYING ('+steps+')';sPathSt.className='sv ok';}"
"    else if(steps>0){sPathSt.textContent=steps+' steps stored';sPathSt.className='sv';}"
"    else{sPathSt.textContent='empty';sPathSt.className='sv';}"
"  }"

"  var btnRecStart=document.getElementById('btnRecStart');"
"  var btnPathPlay=document.getElementById('btnPathPlay');"
"  var btnPathClear=document.getElementById('btnPathClear');"
"  if(btnRecStart){btnRecStart.classList.toggle('recording',rec);}"
"  if(btnPathPlay){btnPathPlay.disabled=(steps===0||rec||play||autoRunning);}"
"  if(btnPathClear){btnPathClear.disabled=(rec||play||autoRunning);}"

"  if(!lastPathRecording&&rec)toast('&#9679; Recording started','rec');"
"  if(lastPathRecording&&!rec)toast('Recording saved — '+steps+' steps','ok');"
"  if(!lastPathPlayback&&play)toast('&#9654; Playback started','ok');"
"  if(lastPathPlayback&&!play&&!autoRunning)toast('Playback complete','ok');"
"  lastPathRecording=rec;lastPathPlayback=play;"
"}"

"function setIR(id,stId,blocked){"
"  var c=document.getElementById(id),s=document.getElementById(stId);"
"  if(!c||!s)return;"
"  c.className='ir-cell '+(blocked?'blocked':'clear');"
"  s.textContent=blocked?'BLOCKED':'CLEAR';"
"}"

"function setAccelBar(fillId,valId,v){"
"  var f=document.getElementById(fillId),vEl=document.getElementById(valId);"
"  if(!f||!vEl)return;"
"  var pct=Math.min(50,Math.abs(v)/2*50);"
"  if(v>=0){f.style.left='50%';f.style.width=pct+'%';}"
"  else{f.style.left=(50-pct)+'%';f.style.width=pct+'%';}"
"  vEl.textContent=(v>=0?'+':'')+v.toFixed(3)+' g';"
"}"

"function updateAutoUI(d){"
"  var running=!!d.auto_running;"
"  var pct=d.auto_pct||0;"
"  var done=d.auto_strips_done||0;"
"  var total=d.auto_strips_total||0;"
"  var state=d.auto_state||'IDLE';"

"  document.getElementById('progressFill').style.width=pct+'%';"
"  document.getElementById('progressPct').textContent=pct+'%';"
"  document.getElementById('stripsDone').textContent=done+' strips done';"
"  document.getElementById('stripsTotal').textContent='/ '+total+' total';"

"  var sl=document.getElementById('autoStateLabel');"
"  var sast=document.getElementById('sAutoSt');"
"  var sab=document.getElementById('startAutoBtn');"
"  var sop=document.getElementById('stopAutoBtn');"
"  var lk=document.getElementById('autoLockMsg');"

"  if(running||d.path_playback){"
"    sl.className='auto-state-label running';"
"    sl.textContent=d.path_playback?'PATH PLAYBACK IN PROGRESS...':'CLEANING IN PROGRESS...';"
"    if(sast){sast.textContent='RUNNING';sast.className='sv ok';}"
"    if(sab)sab.style.display='none';"
"    if(sop)sop.style.display='block';"
"    if(lk)lk.style.display='block';"
"  }else if(state==='DONE'){"
"    sl.className='auto-state-label done';"
"    sl.textContent='CLEANING COMPLETE \u2713';"
"    if(sast){sast.textContent='DONE';sast.className='sv ok';}"
"    if(sab)sab.style.display='block';"
"    if(sop)sop.style.display='none';"
"    if(lk)lk.style.display='none';"
"  }else{"
"    sl.className='auto-state-label idle';"
"    sl.textContent='IDLE \u2014 READY TO CLEAN';"
"    if(sast){sast.textContent='IDLE';sast.className='sv ok';}"
"    if(sab)sab.style.display='block';"
"    if(sop)sop.style.display='none';"
"    if(lk)lk.style.display='none';"
"  }"

"  if(!lastAutoRunning&&running)toast('Auto clean started','ok');"
"  if(lastAutoRunning&&!running&&state==='DONE')toast('Auto clean COMPLETE!','ok');"
"  if(lastAutoRunning&&!running&&state==='IDLE')toast('Auto clean stopped','warn');"
"  lastAutoRunning=running;autoRunning=running;"
"}"

/* Status poll */
"function pollStatus(){"
"  var t0=Date.now();"
"  fetch('/status')"
"    .then(function(r){return r.json();})"
"    .then(function(d){"
"      var ping=Date.now()-t0;"
"      document.getElementById('sPing').textContent=ping+' ms';"
"      document.getElementById('pingDot').className=ping<300?'ok':'err';"
"      document.getElementById('sDir').textContent=d.direction;"
"      document.getElementById('sTail').textContent=d.tail?'ON':'OFF';"

"      var hdg=(d.heading||0);"
"      document.getElementById('sHdg').textContent=hdg.toFixed(2)+'°';"
"      var gz=(d.gyro_z||0);"
"      document.getElementById('sGz').textContent=gz.toFixed(3)+' °/s';"

"      setIR('irFL','irFLst',d.ir_fl);"
"      setIR('irFR','irFRst',d.ir_fr);"
"      setIR('irBL','irBLst',d.ir_bl);"
"      setIR('irBR','irBRst',d.ir_br);"

"      var izF=document.getElementById('izF'),izB=document.getElementById('izB');"
"      if(izF){izF.textContent=d.front_blocked?'BLOCKED':'CLEAR';izF.style.color=d.front_blocked?'var(--bad)':'var(--good)';}"
"      if(izB){izB.textContent=d.back_blocked?'BLOCKED':'CLEAR';izB.style.color=d.back_blocked?'var(--bad)':'var(--good)';}"

"      document.getElementById('sFObs').textContent=d.front_blocked?'BLOCKED':'CLEAR';"
"      document.getElementById('sFObs').className='sv '+(d.front_blocked?'warn2':'ok');"
"      document.getElementById('sBObs').textContent=d.back_blocked?'BLOCKED':'CLEAR';"
"      document.getElementById('sBObs').className='sv '+(d.back_blocked?'warn2':'ok');"
"      var obs=!d.ramming&&(d.front_blocked||d.back_blocked);"
"      document.getElementById('obsBanner').style.display=obs?'block':'none';"
"      if(!d.ramming){"
"        if(!lastFB&&d.front_blocked)toast('FRONT OBSTACLE','warn');"
"        if(!lastBB&&d.back_blocked)toast('BACK OBSTACLE','warn');"
"      }"
"      lastFB=d.front_blocked?1:0;lastBB=d.back_blocked?1:0;"

"      var mpuBadge=document.getElementById('mpuBadge');"
"      if(mpuBadge){mpuBadge.textContent=d.mpu_ready?'CONNECTED \u2713':'NOT DETECTED \u2717';"
"        mpuBadge.className='mpu-ready-badge '+(d.mpu_ready?'ok':'fail');}"
"      var n=document.getElementById('cNeedle'),h=document.getElementById('cHdg');"
"      if(n)n.style.transform='rotate('+(hdg)+'deg)';"
"      if(h)h.textContent=hdg.toFixed(2)+'\u00b0';"
"      var cgz=document.getElementById('cGz');"
"      if(cgz)cgz.textContent='Gz: '+(gz>=0?'+':'')+gz.toFixed(3)+' \u00b0/s';"

"      var b=document.getElementById('tBubble');"
"      if(b){var sc=25,dx=Math.max(-sc,Math.min(sc,(d.accel_x||0)*sc)),"
"        dy=Math.max(-sc,Math.min(sc,-(d.accel_y||0)*sc));"
"        b.style.left='calc(50% + '+dx+'px)';b.style.top='calc(50% + '+dy+'px)';}"
"      setAccelBar('abX','avX',d.accel_x||0);"
"      setAccelBar('abY','avY',d.accel_y||0);"
"      setAccelBar('abZ','avZ',d.accel_z||0);"
"      var vib=d.vib||0;"
"      var vf=document.getElementById('vibFill'),vv=document.getElementById('vibVal');"
"      if(vf){var vc=vib<0.1?'var(--accent)':vib<0.5?'var(--warn)':'var(--bad)';"
"        vf.style.width=Math.min(100,vib/2*100)+'%';vf.style.background=vc;}"
"      if(vv)vv.textContent=vib.toFixed(3)+' g';"
"      document.getElementById('sVib').textContent=vib.toFixed(3)+' g';"
"      var mt=document.getElementById('mpuTemp');"
"      if(mt)mt.textContent=d.mpu_temp+'\u00b0C';"

"      if(d.ramming!=(ramOn?1:0)){ramOn=d.ramming?1:0;updateRamUI();}"
"      if(d.pump!=(pumpOn?1:0)){pumpOn=d.pump?1:0;updatePumpUI();}"
"      if(d.blower!=(blowOn?1:0)){blowOn=d.blower?1:0;updateBlowUI();}"
"      document.getElementById('sPumpSt').textContent=d.pump?'ON':'OFF';"
"      document.getElementById('sPumpSt').className='sv '+(d.pump?'pump-on':'ok');"
"      document.getElementById('sBlowSt').textContent=d.blower?'ON':'OFF';"
"      document.getElementById('sBlowSt').className='sv '+(d.blower?'blow-on':'ok');"

"      updateAutoUI(d);"
"      updatePathUI(d);"

"      var l1='Dir: '+(d.direction.substring(0,7)).padEnd(7)+(d.ramming?' RAM':'    ');"
"      var l2;"
"      if(d.path_recording)l2='REC '+d.path_steps+' STEPS      ';"
"      else if(d.path_playback)l2='PLAYBACK '+d.path_steps+' STEPS';"
"      else if(d.auto_running)l2='AUTO:'+d.auto_pct+'% '+d.auto_strips_done+'/'+d.auto_strips_total;"
"      else if(d.pump&&d.blower)l2='PUMP+BLOW ACTIVE';"
"      else if(d.pump)l2='PUMP ON         ';"
"      else if(d.blower)l2='BLOWER ON       ';"
"      else if(d.front_blocked&&d.back_blocked)l2='F&B BLOCKED     ';"
"      else if(d.front_blocked)l2='FRONT BLOCKED   ';"
"      else if(d.back_blocked)l2='BACK BLOCKED    ';"
"      else l2='F:CLR  B:CLR  Hdg:'+Math.round(d.heading||0);"
"      document.getElementById('l1').textContent=l1.padEnd(16).substring(0,16);"
"      document.getElementById('l2').textContent=(l2||'').padEnd(16).substring(0,16);"
"    })"
"    .catch(function(){document.getElementById('pingDot').className='err';});"
"}"
"setInterval(pollStatus,400);"

/* Sensor Check */
"function runSensorCheck(){"
"  var r=document.getElementById('chkResult');"
"  r.innerHTML='<div style=\"font-family:Share Tech Mono;font-size:9px;color:var(--dim)\">Checking...</div>';"
"  fetch('/sensor_check')"
"    .then(function(res){return res.json();})"
"    .then(function(d){"
"      document.getElementById('roverDims').textContent=d.rover_w_cm+'cm \u00d7 '+d.rover_d_cm+'cm';"
"      var rows='';"
"      function row(name,status,note){"
"        var cls=status==='OK'?'chk-ok':status==='FAIL'?'chk-fail':'chk-na';"
"        return '<tr><td>'+name+'</td><td class=\"'+cls+'\">'+status+'</td><td style=\"color:var(--dim)\">'+note+'</td></tr>';"
"      }"
"      rows+=row('IR',d.ir_enabled?'OK':'N/A',d.ir_enabled?'IR_ENABLED=1':'IR_ENABLED=0');"
"      if(d.ir_enabled){"
"        rows+=row('IR Front-L',d.ir_fl.blocked?'BLOCKED':'CLEAR','Pin '+d.ir_fl.pin);"
"        rows+=row('IR Front-R',d.ir_fr.blocked?'BLOCKED':'CLEAR','Pin '+d.ir_fr.pin);"
"        rows+=row('IR Back-L', d.ir_bl.blocked?'BLOCKED':'CLEAR','Pin '+d.ir_bl.pin);"
"        rows+=row('IR Back-R', d.ir_br.blocked?'BLOCKED':'CLEAR','Pin '+d.ir_br.pin);"
"      }"
"      rows+=row('MPU',d.mpu_enabled?'OK':'N/A',d.mpu_enabled?'MPU_ENABLED=1':'MPU_ENABLED=0');"
"      if(d.mpu_enabled){"
"        rows+=row('WHO_AM_I',d.mpu_ready?'OK':'FAIL',d.mpu_ready?'Sensor found':'No response - check SDA/SCL');"
"        if(d.mpu_ready){"
"          var azOk=Math.abs(d.mpu_accel_z-1.0)<0.3;"
"          rows+=row('Accel Z',azOk?'OK':'WARN','Expected ~1.0g flat, got '+d.mpu_accel_z.toFixed(3)+'g');"
"          rows+=row('Heading','OK',d.mpu_heading.toFixed(2)+'\u00b0 (relative)');"
"          rows+=row('Temp','OK',d.mpu_temp_c+'\u00b0C');"
"        }"
"      }"
"      r.innerHTML='<table class=\"chk-table\"><thead><tr><th>SENSOR</th><th>STATUS</th><th>DETAIL</th></tr></thead><tbody>'+rows+'</tbody></table>';"
"    })"
"    .catch(function(){r.innerHTML='<div style=\"color:var(--bad);font-family:Share Tech Mono;font-size:10px\">Request failed</div>';});"
"}"

/* Grid editor */
"function calcAndDraw(){"
"  var cols=parseInt(document.getElementById('gCols').value)||1;"
"  var rows=parseInt(document.getElementById('gRows').value)||1;"
"  var pw=parseInt(document.getElementById('gPW').value)||200;"
"  var ph=parseInt(document.getElementById('gPH').value)||170;"
"  var gap=parseInt(document.getElementById('gGap').value)||5;"
"  var roverW=58,roverD=51;"
"  var strips=Math.ceil(ph/roverW);"  /* strips go along HEIGHT axis */
"  var totalStrips=strips*cols*rows;"
"  var fwdSec=pw*0.015;" /* ~15ms/cm forward */
"  var stepSec=roverW*0.015;" /* step */
"  var estSec=(fwdSec+1.5)*strips*cols*rows;" /* +1.5s per step settle */
"  var calcEl=document.getElementById('calcInfo');"
"  if(calcEl){"
"    calcEl.innerHTML="
"      '<span style=\"color:var(--accent3)\">Rover: '+roverW+'cm \u00d7 '+roverD+'cm</span><br>'"
"      +'Strips per panel: '+strips+' (each '+roverW+'cm wide)<br>'"
"      +'Panel sweep width: '+pw+'cm, height: '+ph+'cm<br>'"
"      +'Total strips: '+totalStrips+'<br>'"
"      +'Est. clean time: ~'+Math.round(estSec/60)+' min '+Math.round(estSec%60)+' sec';"
"  }"
"  drawGrid({cols:cols,rows:rows,pw:pw,ph:ph,gap:gap});"
"}"

"function saveGrid(){"
"  var cols=parseInt(document.getElementById('gCols').value)||2;"
"  var rows=parseInt(document.getElementById('gRows').value)||1;"
"  var pw=parseInt(document.getElementById('gPW').value)||200;"
"  var ph=parseInt(document.getElementById('gPH').value)||170;"
"  var gap=parseInt(document.getElementById('gGap').value)||5;"
"  var wash=document.getElementById('gWash').checked?1:0;"
"  var blow=document.getElementById('gBlow').checked?1:0;"
"  fetch('/set_grid?cols='+cols+'&rows='+rows+'&pw='+pw+'&ph='+ph+'&gap='+gap+'&wash='+wash+'&blow='+blow)"
"    .then(function(r){return r.json();})"
"    .then(function(d){"
"      document.getElementById('gridMsg').textContent="
"        'Saved: '+d.cols+'\u00d7'+d.rows+' panels, '+d.total_strips+' strips total';"
"      toast('Grid saved \u2014 '+d.total_strips+' strips','ok');"
"      drawGrid(d);"
"    })"
"    .catch(function(){toast('Save failed','err');});"
"}"

"function startAuto(){"
"  if(!confirm('Start automatic cleaning?\\n\\nPlace rover at TOP-LEFT of first panel facing DOWN the panel.'))return;"
"  fetch('/auto')"
"    .then(function(r){return r.text();})"
"    .then(function(msg){"
"      if(msg==='ALREADY_RUNNING'){toast('Already running','warn');return;}"
"      if(msg.indexOf('ERROR')===0){toast(msg,'err');return;}"
"    }).catch(function(){toast('Start failed','err');});"
"}"
"function stopAuto(){"
"  fetch('/stop_auto').then(function(){toast('Stop requested','warn');}).catch(function(){});"
"}"

"function loadGrid(){"
"  fetch('/get_grid').then(function(r){return r.json();})"
"    .then(function(d){"
"      document.getElementById('gCols').value=d.cols;"
"      document.getElementById('gRows').value=d.rows;"
"      document.getElementById('gPW').value=d.pw;"
"      document.getElementById('gPH').value=d.ph;"
"      document.getElementById('gGap').value=d.gap;"
"      document.getElementById('gWash').checked=d.wash===1;"
"      document.getElementById('gBlow').checked=d.blow===1;"
"      if(d.rover_w_cm)"
"        document.getElementById('roverDims').textContent=d.rover_w_cm+'cm \u00d7 '+d.rover_d_cm+'cm';"
"      calcAndDraw();"
"    }).catch(function(){});"
"}"

/* Canvas */
"function drawGrid(d){"
"  var canvas=document.getElementById('gpCanvas');"
"  var ctx=canvas.getContext('2d');"
"  var W=canvas.width,H=canvas.height;"
"  ctx.clearRect(0,0,W,H);"
"  var roverW=58;"
"  var pw=d.pw||d.panel_w_cm||200;"
"  var ph=d.ph||d.panel_h_cm||170;"
"  var cols=d.cols||d.panel_cols||1;"
"  var rows=d.rows||d.panel_rows||1;"
"  var gap=d.gap||d.gap_between_cm||5;"
"  var totalW=cols*pw+(cols-1)*gap;"
"  var totalH=rows*ph+(rows-1)*gap;"
"  var sc=Math.min((W-20)/totalW,(H-20)/totalH);"
"  var offX=(W-totalW*sc)/2,offY=(H-totalH*sc)/2;"
"  var strips=Math.ceil(ph/roverW);"
"  var sh=ph/strips;"

"  for(var r=0;r<rows;r++){for(var c=0;c<cols;c++){"
"    var px=offX+(c*(pw+gap))*sc;"
"    var py=offY+(r*(ph+gap))*sc;"
"    var pws=pw*sc,phs=ph*sc;"
"    ctx.fillStyle='rgba(0,60,30,0.5)';ctx.fillRect(px,py,pws,phs);"
"    ctx.strokeStyle='rgba(0,212,120,0.5)';ctx.lineWidth=1.5;ctx.strokeRect(px,py,pws,phs);"
"    ctx.strokeStyle='rgba(0,212,120,0.2)';ctx.lineWidth=0.5;ctx.setLineDash([3,3]);"
"    for(var s=1;s<strips;s++){var sy=py+s*sh*sc;ctx.beginPath();ctx.moveTo(px,sy);ctx.lineTo(px+pws,sy);ctx.stroke();}"
"    ctx.setLineDash([]);"
"    for(var s=0;s<strips;s++){"
"      var sy=py+(s+0.5)*sh*sc;"
"      ctx.strokeStyle='rgba(0,212,120,0.8)';ctx.lineWidth=1.5;"
"      ctx.beginPath();ctx.moveTo(px+pws*0.15,sy);ctx.lineTo(px+pws*0.85,sy);ctx.stroke();"
"      ctx.beginPath();ctx.moveTo(px+pws*0.75,sy-4);ctx.lineTo(px+pws*0.85,sy);ctx.lineTo(px+pws*0.75,sy+4);ctx.stroke();"
"      if(s<strips-1){"
"        ctx.strokeStyle='rgba(0,170,255,0.6)';ctx.lineWidth=1;"
"        var lsy=py+(s+1)*sh*sc,rex=px+pws;"
"        ctx.beginPath();ctx.moveTo(rex-4,lsy-6);ctx.lineTo(rex,lsy);ctx.lineTo(rex-4,lsy+6);ctx.stroke();"
"        ctx.beginPath();ctx.moveTo(rex,sy);ctx.lineTo(rex,lsy);ctx.stroke();"
"      }"
"    }"
"    if(c<cols-1){"
"      var gapXStart=px+pws,gapXEnd=gapXStart+gap*sc;"
"      ctx.strokeStyle='rgba(0,170,255,0.5)';ctx.lineWidth=1;ctx.setLineDash([4,2]);"
"      ctx.beginPath();ctx.moveTo(gapXStart,py+phs/2);ctx.lineTo(gapXEnd,py+phs/2);ctx.stroke();"
"      ctx.setLineDash([]);"
"      ctx.beginPath();ctx.moveTo(gapXEnd-5,py+phs/2-3);ctx.lineTo(gapXEnd,py+phs/2);ctx.lineTo(gapXEnd-5,py+phs/2+3);ctx.stroke();"
"    }"
"  }}"
"  ctx.fillStyle='#ffcc00';"
"  ctx.beginPath();ctx.arc(offX+8,offY+8,5,0,2*Math.PI);ctx.fill();"
"  var estSec=strips*(pw*0.015+1.5)*cols*rows;"
"  document.getElementById('gpInfo').innerHTML="
"    'Total panels: '+(cols*rows)+'  |  Strips/panel: '+strips+'<br>'"
"    +'Panel: '+pw+'cm wide \u00d7 '+ph+'cm tall<br>'"
"    +'Est. clean: ~'+Math.round(estSec/60)+' min '+Math.round(estSec%60)+' sec';"
"}"

"['gCols','gRows','gPW','gPH','gGap'].forEach(function(id){"
"  document.getElementById(id).addEventListener('input',calcAndDraw);"
"});"

/* Joystick */
"(function(){"
"var joy=document.getElementById('joy'),joyH=document.getElementById('joyH');"
"var JR=52,DEAD=12,active=false,cx=0,cy=0,lastJoyCmd='';"
"function setH(dx,dy){var p=34;joyH.style.left=(50+dx/JR*p)+'%';joyH.style.top=(50+dy/JR*p)+'%';}"
"function vecToCmd(dx,dy){"
"  var fy=-dy,mag=Math.sqrt(dx*dx+fy*fy);"
"  if(mag<DEAD)return 'stop';"
"  var a=Math.atan2(fy,dx)*180/Math.PI;"
"  if(a>65&&a<115)return 'forward';"
"  if(a<-65&&a>-115)return 'backward';"
"  if(a>=115||a<=-115)return 'left';"
"  if(a>=-30&&a<=30)return 'right';"
"  if(a>30&&a<=65)return 'drift_right';"
"  if(a<-30&&a>=-65)return 'drift_right';"
"  return 'stop';"
"}"
"function onStart(e){e.preventDefault();"
"  if(autoRunning||pathPlayback)return;"
"  active=true;"
"  var r=joy.getBoundingClientRect();cx=r.left+r.width/2;cy=r.top+r.height/2;"
"  if(joy.setPointerCapture&&e.pointerId)joy.setPointerCapture(e.pointerId);}"
"function onMove(e){if(!active)return;e.preventDefault();"
"  var t=e.touches?e.touches[0]:e;var dx=t.clientX-cx,dy=t.clientY-cy;"
"  var m=Math.sqrt(dx*dx+dy*dy);if(m>JR){dx=dx*JR/m;dy=dy*JR/m;}"
"  setH(dx,dy);var cmd=vecToCmd(dx,dy);if(cmd!==lastJoyCmd){lastJoyCmd=cmd;mv(cmd);}}"
"function onEnd(e){e.preventDefault();active=false;lastJoyCmd='stop';setH(0,0);mv('stop');}"
"joy.addEventListener('pointerdown',onStart,{passive:false});"
"joy.addEventListener('pointermove',onMove,{passive:false});"
"joy.addEventListener('pointerup',onEnd,{passive:false});"
"joy.addEventListener('pointercancel',onEnd,{passive:false});"
"document.addEventListener('mouseup',onEnd,{passive:false});"
"})();"

"window.addEventListener('load',function(){"
"  updateRamUI();updatePumpUI();updateBlowUI();"
"  loadGrid();pollStatus();"
"});"
"</script>"
"</body></html>";

const char *html_get_page(void)
{
    return HTML_PAGE;
}